// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package vpc_attachment

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.CoreNetworkID, b.ko.Spec.CoreNetworkID) {
		delta.Add("Spec.CoreNetworkID", a.ko.Spec.CoreNetworkID, b.ko.Spec.CoreNetworkID)
	} else if a.ko.Spec.CoreNetworkID != nil && b.ko.Spec.CoreNetworkID != nil {
		if *a.ko.Spec.CoreNetworkID != *b.ko.Spec.CoreNetworkID {
			delta.Add("Spec.CoreNetworkID", a.ko.Spec.CoreNetworkID, b.ko.Spec.CoreNetworkID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Options, b.ko.Spec.Options) {
		delta.Add("Spec.Options", a.ko.Spec.Options, b.ko.Spec.Options)
	} else if a.ko.Spec.Options != nil && b.ko.Spec.Options != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Options.ApplianceModeSupport, b.ko.Spec.Options.ApplianceModeSupport) {
			delta.Add("Spec.Options.ApplianceModeSupport", a.ko.Spec.Options.ApplianceModeSupport, b.ko.Spec.Options.ApplianceModeSupport)
		} else if a.ko.Spec.Options.ApplianceModeSupport != nil && b.ko.Spec.Options.ApplianceModeSupport != nil {
			if *a.ko.Spec.Options.ApplianceModeSupport != *b.ko.Spec.Options.ApplianceModeSupport {
				delta.Add("Spec.Options.ApplianceModeSupport", a.ko.Spec.Options.ApplianceModeSupport, b.ko.Spec.Options.ApplianceModeSupport)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Options.DNSSupport, b.ko.Spec.Options.DNSSupport) {
			delta.Add("Spec.Options.DNSSupport", a.ko.Spec.Options.DNSSupport, b.ko.Spec.Options.DNSSupport)
		} else if a.ko.Spec.Options.DNSSupport != nil && b.ko.Spec.Options.DNSSupport != nil {
			if *a.ko.Spec.Options.DNSSupport != *b.ko.Spec.Options.DNSSupport {
				delta.Add("Spec.Options.DNSSupport", a.ko.Spec.Options.DNSSupport, b.ko.Spec.Options.DNSSupport)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Options.IPv6Support, b.ko.Spec.Options.IPv6Support) {
			delta.Add("Spec.Options.IPv6Support", a.ko.Spec.Options.IPv6Support, b.ko.Spec.Options.IPv6Support)
		} else if a.ko.Spec.Options.IPv6Support != nil && b.ko.Spec.Options.IPv6Support != nil {
			if *a.ko.Spec.Options.IPv6Support != *b.ko.Spec.Options.IPv6Support {
				delta.Add("Spec.Options.IPv6Support", a.ko.Spec.Options.IPv6Support, b.ko.Spec.Options.IPv6Support)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Options.SecurityGroupReferencingSupport, b.ko.Spec.Options.SecurityGroupReferencingSupport) {
			delta.Add("Spec.Options.SecurityGroupReferencingSupport", a.ko.Spec.Options.SecurityGroupReferencingSupport, b.ko.Spec.Options.SecurityGroupReferencingSupport)
		} else if a.ko.Spec.Options.SecurityGroupReferencingSupport != nil && b.ko.Spec.Options.SecurityGroupReferencingSupport != nil {
			if *a.ko.Spec.Options.SecurityGroupReferencingSupport != *b.ko.Spec.Options.SecurityGroupReferencingSupport {
				delta.Add("Spec.Options.SecurityGroupReferencingSupport", a.ko.Spec.Options.SecurityGroupReferencingSupport, b.ko.Spec.Options.SecurityGroupReferencingSupport)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoutingPolicyLabel, b.ko.Spec.RoutingPolicyLabel) {
		delta.Add("Spec.RoutingPolicyLabel", a.ko.Spec.RoutingPolicyLabel, b.ko.Spec.RoutingPolicyLabel)
	} else if a.ko.Spec.RoutingPolicyLabel != nil && b.ko.Spec.RoutingPolicyLabel != nil {
		if *a.ko.Spec.RoutingPolicyLabel != *b.ko.Spec.RoutingPolicyLabel {
			delta.Add("Spec.RoutingPolicyLabel", a.ko.Spec.RoutingPolicyLabel, b.ko.Spec.RoutingPolicyLabel)
		}
	}
	if len(a.ko.Spec.SubnetARNs) != len(b.ko.Spec.SubnetARNs) {
		delta.Add("Spec.SubnetARNs", a.ko.Spec.SubnetARNs, b.ko.Spec.SubnetARNs)
	} else if len(a.ko.Spec.SubnetARNs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.SubnetARNs, b.ko.Spec.SubnetARNs) {
			delta.Add("Spec.SubnetARNs", a.ko.Spec.SubnetARNs, b.ko.Spec.SubnetARNs)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.VPCARN, b.ko.Spec.VPCARN) {
		delta.Add("Spec.VPCARN", a.ko.Spec.VPCARN, b.ko.Spec.VPCARN)
	} else if a.ko.Spec.VPCARN != nil && b.ko.Spec.VPCARN != nil {
		if *a.ko.Spec.VPCARN != *b.ko.Spec.VPCARN {
			delta.Add("Spec.VPCARN", a.ko.Spec.VPCARN, b.ko.Spec.VPCARN)
		}
	}

	return delta
}
