// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package vpc_attachment

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/networkmanager"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/networkmanager/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/networkmanager-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.VPCAttachment{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetVpcAttachmentOutput
	resp, err = rm.sdkapi.GetVpcAttachment(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetVpcAttachment", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.VpcAttachment.Attachment != nil {
		f0 := &svcapitypes.Attachment{}
		if resp.VpcAttachment.Attachment.AttachmentId != nil {
			f0.AttachmentID = resp.VpcAttachment.Attachment.AttachmentId
		}
		if resp.VpcAttachment.Attachment.AttachmentPolicyRuleNumber != nil {
			attachmentPolicyRuleNumberCopy := int64(*resp.VpcAttachment.Attachment.AttachmentPolicyRuleNumber)
			f0.AttachmentPolicyRuleNumber = &attachmentPolicyRuleNumberCopy
		}
		if resp.VpcAttachment.Attachment.AttachmentType != "" {
			f0.AttachmentType = aws.String(string(resp.VpcAttachment.Attachment.AttachmentType))
		}
		if resp.VpcAttachment.Attachment.CoreNetworkArn != nil {
			f0.CoreNetworkARN = resp.VpcAttachment.Attachment.CoreNetworkArn
		}
		if resp.VpcAttachment.Attachment.CoreNetworkId != nil {
			f0.CoreNetworkID = resp.VpcAttachment.Attachment.CoreNetworkId
		}
		if resp.VpcAttachment.Attachment.CreatedAt != nil {
			f0.CreatedAt = &metav1.Time{*resp.VpcAttachment.Attachment.CreatedAt}
		}
		if resp.VpcAttachment.Attachment.EdgeLocation != nil {
			f0.EdgeLocation = resp.VpcAttachment.Attachment.EdgeLocation
		}
		if resp.VpcAttachment.Attachment.EdgeLocations != nil {
			f0.EdgeLocations = aws.StringSlice(resp.VpcAttachment.Attachment.EdgeLocations)
		}
		if resp.VpcAttachment.Attachment.LastModificationErrors != nil {
			f0f8 := []*svcapitypes.AttachmentError{}
			for _, f0f8iter := range resp.VpcAttachment.Attachment.LastModificationErrors {
				f0f8elem := &svcapitypes.AttachmentError{}
				if f0f8iter.Code != "" {
					f0f8elem.Code = aws.String(string(f0f8iter.Code))
				}
				if f0f8iter.Message != nil {
					f0f8elem.Message = f0f8iter.Message
				}
				if f0f8iter.RequestId != nil {
					f0f8elem.RequestID = f0f8iter.RequestId
				}
				if f0f8iter.ResourceArn != nil {
					f0f8elem.ResourceARN = f0f8iter.ResourceArn
				}
				f0f8 = append(f0f8, f0f8elem)
			}
			f0.LastModificationErrors = f0f8
		}
		if resp.VpcAttachment.Attachment.NetworkFunctionGroupName != nil {
			f0.NetworkFunctionGroupName = resp.VpcAttachment.Attachment.NetworkFunctionGroupName
		}
		if resp.VpcAttachment.Attachment.OwnerAccountId != nil {
			f0.OwnerAccountID = resp.VpcAttachment.Attachment.OwnerAccountId
		}
		if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange != nil {
			f0f11 := &svcapitypes.ProposedNetworkFunctionGroupChange{}
			if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.AttachmentPolicyRuleNumber != nil {
				attachmentPolicyRuleNumberCopy := int64(*resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.AttachmentPolicyRuleNumber)
				f0f11.AttachmentPolicyRuleNumber = &attachmentPolicyRuleNumberCopy
			}
			if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.NetworkFunctionGroupName != nil {
				f0f11.NetworkFunctionGroupName = resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.NetworkFunctionGroupName
			}
			if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.Tags != nil {
				f0f11f2 := []*svcapitypes.Tag{}
				for _, f0f11f2iter := range resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.Tags {
					f0f11f2elem := &svcapitypes.Tag{}
					if f0f11f2iter.Key != nil {
						f0f11f2elem.Key = f0f11f2iter.Key
					}
					if f0f11f2iter.Value != nil {
						f0f11f2elem.Value = f0f11f2iter.Value
					}
					f0f11f2 = append(f0f11f2, f0f11f2elem)
				}
				f0f11.Tags = f0f11f2
			}
			f0.ProposedNetworkFunctionGroupChange = f0f11
		}
		if resp.VpcAttachment.Attachment.ProposedSegmentChange != nil {
			f0f12 := &svcapitypes.ProposedSegmentChange{}
			if resp.VpcAttachment.Attachment.ProposedSegmentChange.AttachmentPolicyRuleNumber != nil {
				attachmentPolicyRuleNumberCopy := int64(*resp.VpcAttachment.Attachment.ProposedSegmentChange.AttachmentPolicyRuleNumber)
				f0f12.AttachmentPolicyRuleNumber = &attachmentPolicyRuleNumberCopy
			}
			if resp.VpcAttachment.Attachment.ProposedSegmentChange.SegmentName != nil {
				f0f12.SegmentName = resp.VpcAttachment.Attachment.ProposedSegmentChange.SegmentName
			}
			if resp.VpcAttachment.Attachment.ProposedSegmentChange.Tags != nil {
				f0f12f2 := []*svcapitypes.Tag{}
				for _, f0f12f2iter := range resp.VpcAttachment.Attachment.ProposedSegmentChange.Tags {
					f0f12f2elem := &svcapitypes.Tag{}
					if f0f12f2iter.Key != nil {
						f0f12f2elem.Key = f0f12f2iter.Key
					}
					if f0f12f2iter.Value != nil {
						f0f12f2elem.Value = f0f12f2iter.Value
					}
					f0f12f2 = append(f0f12f2, f0f12f2elem)
				}
				f0f12.Tags = f0f12f2
			}
			f0.ProposedSegmentChange = f0f12
		}
		if resp.VpcAttachment.Attachment.ResourceArn != nil {
			f0.ResourceARN = resp.VpcAttachment.Attachment.ResourceArn
		}
		if resp.VpcAttachment.Attachment.SegmentName != nil {
			f0.SegmentName = resp.VpcAttachment.Attachment.SegmentName
		}
		if resp.VpcAttachment.Attachment.State != "" {
			f0.State = aws.String(string(resp.VpcAttachment.Attachment.State))
		}
		if resp.VpcAttachment.Attachment.Tags != nil {
			f0f16 := []*svcapitypes.Tag{}
			for _, f0f16iter := range resp.VpcAttachment.Attachment.Tags {
				f0f16elem := &svcapitypes.Tag{}
				if f0f16iter.Key != nil {
					f0f16elem.Key = f0f16iter.Key
				}
				if f0f16iter.Value != nil {
					f0f16elem.Value = f0f16iter.Value
				}
				f0f16 = append(f0f16, f0f16elem)
			}
			f0.Tags = f0f16
		}
		if resp.VpcAttachment.Attachment.UpdatedAt != nil {
			f0.UpdatedAt = &metav1.Time{*resp.VpcAttachment.Attachment.UpdatedAt}
		}
		ko.Status.Attachment = f0
	} else {
		ko.Status.Attachment = nil
	}
	if resp.VpcAttachment.Options != nil {
		f1 := &svcapitypes.VPCOptions{}
		f1.ApplianceModeSupport = resp.VpcAttachment.Options.ApplianceModeSupport
		f1.DNSSupport = resp.VpcAttachment.Options.DnsSupport
		f1.IPv6Support = resp.VpcAttachment.Options.Ipv6Support
		f1.SecurityGroupReferencingSupport = resp.VpcAttachment.Options.SecurityGroupReferencingSupport
		ko.Spec.Options = f1
	} else {
		ko.Spec.Options = nil
	}
	if resp.VpcAttachment.SubnetArns != nil {
		ko.Spec.SubnetARNs = aws.StringSlice(resp.VpcAttachment.SubnetArns)
	} else {
		ko.Spec.SubnetARNs = nil
	}

	rm.setStatusDefaults(ko)
	rm.syncTopLevelStatus(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.AttachmentID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetVpcAttachmentInput, error) {
	res := &svcsdk.GetVpcAttachmentInput{}

	if r.ko.Status.AttachmentID != nil {
		res.AttachmentId = r.ko.Status.AttachmentID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateVpcAttachmentOutput
	_ = resp
	resp, err = rm.sdkapi.CreateVpcAttachment(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateVpcAttachment", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.VpcAttachment.Attachment != nil {
		f0 := &svcapitypes.Attachment{}
		if resp.VpcAttachment.Attachment.AttachmentId != nil {
			f0.AttachmentID = resp.VpcAttachment.Attachment.AttachmentId
		}
		if resp.VpcAttachment.Attachment.AttachmentPolicyRuleNumber != nil {
			attachmentPolicyRuleNumberCopy := int64(*resp.VpcAttachment.Attachment.AttachmentPolicyRuleNumber)
			f0.AttachmentPolicyRuleNumber = &attachmentPolicyRuleNumberCopy
		}
		if resp.VpcAttachment.Attachment.AttachmentType != "" {
			f0.AttachmentType = aws.String(string(resp.VpcAttachment.Attachment.AttachmentType))
		}
		if resp.VpcAttachment.Attachment.CoreNetworkArn != nil {
			f0.CoreNetworkARN = resp.VpcAttachment.Attachment.CoreNetworkArn
		}
		if resp.VpcAttachment.Attachment.CoreNetworkId != nil {
			f0.CoreNetworkID = resp.VpcAttachment.Attachment.CoreNetworkId
		}
		if resp.VpcAttachment.Attachment.CreatedAt != nil {
			f0.CreatedAt = &metav1.Time{*resp.VpcAttachment.Attachment.CreatedAt}
		}
		if resp.VpcAttachment.Attachment.EdgeLocation != nil {
			f0.EdgeLocation = resp.VpcAttachment.Attachment.EdgeLocation
		}
		if resp.VpcAttachment.Attachment.EdgeLocations != nil {
			f0.EdgeLocations = aws.StringSlice(resp.VpcAttachment.Attachment.EdgeLocations)
		}
		if resp.VpcAttachment.Attachment.LastModificationErrors != nil {
			f0f8 := []*svcapitypes.AttachmentError{}
			for _, f0f8iter := range resp.VpcAttachment.Attachment.LastModificationErrors {
				f0f8elem := &svcapitypes.AttachmentError{}
				if f0f8iter.Code != "" {
					f0f8elem.Code = aws.String(string(f0f8iter.Code))
				}
				if f0f8iter.Message != nil {
					f0f8elem.Message = f0f8iter.Message
				}
				if f0f8iter.RequestId != nil {
					f0f8elem.RequestID = f0f8iter.RequestId
				}
				if f0f8iter.ResourceArn != nil {
					f0f8elem.ResourceARN = f0f8iter.ResourceArn
				}
				f0f8 = append(f0f8, f0f8elem)
			}
			f0.LastModificationErrors = f0f8
		}
		if resp.VpcAttachment.Attachment.NetworkFunctionGroupName != nil {
			f0.NetworkFunctionGroupName = resp.VpcAttachment.Attachment.NetworkFunctionGroupName
		}
		if resp.VpcAttachment.Attachment.OwnerAccountId != nil {
			f0.OwnerAccountID = resp.VpcAttachment.Attachment.OwnerAccountId
		}
		if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange != nil {
			f0f11 := &svcapitypes.ProposedNetworkFunctionGroupChange{}
			if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.AttachmentPolicyRuleNumber != nil {
				attachmentPolicyRuleNumberCopy := int64(*resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.AttachmentPolicyRuleNumber)
				f0f11.AttachmentPolicyRuleNumber = &attachmentPolicyRuleNumberCopy
			}
			if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.NetworkFunctionGroupName != nil {
				f0f11.NetworkFunctionGroupName = resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.NetworkFunctionGroupName
			}
			if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.Tags != nil {
				f0f11f2 := []*svcapitypes.Tag{}
				for _, f0f11f2iter := range resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.Tags {
					f0f11f2elem := &svcapitypes.Tag{}
					if f0f11f2iter.Key != nil {
						f0f11f2elem.Key = f0f11f2iter.Key
					}
					if f0f11f2iter.Value != nil {
						f0f11f2elem.Value = f0f11f2iter.Value
					}
					f0f11f2 = append(f0f11f2, f0f11f2elem)
				}
				f0f11.Tags = f0f11f2
			}
			f0.ProposedNetworkFunctionGroupChange = f0f11
		}
		if resp.VpcAttachment.Attachment.ProposedSegmentChange != nil {
			f0f12 := &svcapitypes.ProposedSegmentChange{}
			if resp.VpcAttachment.Attachment.ProposedSegmentChange.AttachmentPolicyRuleNumber != nil {
				attachmentPolicyRuleNumberCopy := int64(*resp.VpcAttachment.Attachment.ProposedSegmentChange.AttachmentPolicyRuleNumber)
				f0f12.AttachmentPolicyRuleNumber = &attachmentPolicyRuleNumberCopy
			}
			if resp.VpcAttachment.Attachment.ProposedSegmentChange.SegmentName != nil {
				f0f12.SegmentName = resp.VpcAttachment.Attachment.ProposedSegmentChange.SegmentName
			}
			if resp.VpcAttachment.Attachment.ProposedSegmentChange.Tags != nil {
				f0f12f2 := []*svcapitypes.Tag{}
				for _, f0f12f2iter := range resp.VpcAttachment.Attachment.ProposedSegmentChange.Tags {
					f0f12f2elem := &svcapitypes.Tag{}
					if f0f12f2iter.Key != nil {
						f0f12f2elem.Key = f0f12f2iter.Key
					}
					if f0f12f2iter.Value != nil {
						f0f12f2elem.Value = f0f12f2iter.Value
					}
					f0f12f2 = append(f0f12f2, f0f12f2elem)
				}
				f0f12.Tags = f0f12f2
			}
			f0.ProposedSegmentChange = f0f12
		}
		if resp.VpcAttachment.Attachment.ResourceArn != nil {
			f0.ResourceARN = resp.VpcAttachment.Attachment.ResourceArn
		}
		if resp.VpcAttachment.Attachment.SegmentName != nil {
			f0.SegmentName = resp.VpcAttachment.Attachment.SegmentName
		}
		if resp.VpcAttachment.Attachment.State != "" {
			f0.State = aws.String(string(resp.VpcAttachment.Attachment.State))
		}
		if resp.VpcAttachment.Attachment.Tags != nil {
			f0f16 := []*svcapitypes.Tag{}
			for _, f0f16iter := range resp.VpcAttachment.Attachment.Tags {
				f0f16elem := &svcapitypes.Tag{}
				if f0f16iter.Key != nil {
					f0f16elem.Key = f0f16iter.Key
				}
				if f0f16iter.Value != nil {
					f0f16elem.Value = f0f16iter.Value
				}
				f0f16 = append(f0f16, f0f16elem)
			}
			f0.Tags = f0f16
		}
		if resp.VpcAttachment.Attachment.UpdatedAt != nil {
			f0.UpdatedAt = &metav1.Time{*resp.VpcAttachment.Attachment.UpdatedAt}
		}
		ko.Status.Attachment = f0
	} else {
		ko.Status.Attachment = nil
	}
	if resp.VpcAttachment.Options != nil {
		f1 := &svcapitypes.VPCOptions{}
		f1.ApplianceModeSupport = resp.VpcAttachment.Options.ApplianceModeSupport
		f1.DNSSupport = resp.VpcAttachment.Options.DnsSupport
		f1.IPv6Support = resp.VpcAttachment.Options.Ipv6Support
		f1.SecurityGroupReferencingSupport = resp.VpcAttachment.Options.SecurityGroupReferencingSupport
		ko.Spec.Options = f1
	} else {
		ko.Spec.Options = nil
	}
	if resp.VpcAttachment.SubnetArns != nil {
		ko.Spec.SubnetARNs = aws.StringSlice(resp.VpcAttachment.SubnetArns)
	} else {
		ko.Spec.SubnetARNs = nil
	}

	rm.setStatusDefaults(ko)
	rm.syncTopLevelStatus(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateVpcAttachmentInput, error) {
	res := &svcsdk.CreateVpcAttachmentInput{}

	if r.ko.Spec.CoreNetworkID != nil {
		res.CoreNetworkId = r.ko.Spec.CoreNetworkID
	}
	if r.ko.Spec.Options != nil {
		f1 := &svcsdktypes.VpcOptions{}
		if r.ko.Spec.Options.ApplianceModeSupport != nil {
			f1.ApplianceModeSupport = r.ko.Spec.Options.ApplianceModeSupport
		}
		if r.ko.Spec.Options.DNSSupport != nil {
			f1.DnsSupport = r.ko.Spec.Options.DNSSupport
		}
		if r.ko.Spec.Options.IPv6Support != nil {
			f1.Ipv6Support = r.ko.Spec.Options.IPv6Support
		}
		if r.ko.Spec.Options.SecurityGroupReferencingSupport != nil {
			f1.SecurityGroupReferencingSupport = r.ko.Spec.Options.SecurityGroupReferencingSupport
		}
		res.Options = f1
	}
	if r.ko.Spec.RoutingPolicyLabel != nil {
		res.RoutingPolicyLabel = r.ko.Spec.RoutingPolicyLabel
	}
	if r.ko.Spec.SubnetARNs != nil {
		res.SubnetArns = aws.ToStringSlice(r.ko.Spec.SubnetARNs)
	}
	if r.ko.Spec.Tags != nil {
		f4 := []svcsdktypes.Tag{}
		for _, f4iter := range r.ko.Spec.Tags {
			f4elem := &svcsdktypes.Tag{}
			if f4iter.Key != nil {
				f4elem.Key = f4iter.Key
			}
			if f4iter.Value != nil {
				f4elem.Value = f4iter.Value
			}
			f4 = append(f4, *f4elem)
		}
		res.Tags = f4
	}
	if r.ko.Spec.VPCARN != nil {
		res.VpcArn = r.ko.Spec.VPCARN
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateVpcAttachmentOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateVpcAttachment(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateVpcAttachment", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.VpcAttachment.Attachment != nil {
		f0 := &svcapitypes.Attachment{}
		if resp.VpcAttachment.Attachment.AttachmentId != nil {
			f0.AttachmentID = resp.VpcAttachment.Attachment.AttachmentId
		}
		if resp.VpcAttachment.Attachment.AttachmentPolicyRuleNumber != nil {
			attachmentPolicyRuleNumberCopy := int64(*resp.VpcAttachment.Attachment.AttachmentPolicyRuleNumber)
			f0.AttachmentPolicyRuleNumber = &attachmentPolicyRuleNumberCopy
		}
		if resp.VpcAttachment.Attachment.AttachmentType != "" {
			f0.AttachmentType = aws.String(string(resp.VpcAttachment.Attachment.AttachmentType))
		}
		if resp.VpcAttachment.Attachment.CoreNetworkArn != nil {
			f0.CoreNetworkARN = resp.VpcAttachment.Attachment.CoreNetworkArn
		}
		if resp.VpcAttachment.Attachment.CoreNetworkId != nil {
			f0.CoreNetworkID = resp.VpcAttachment.Attachment.CoreNetworkId
		}
		if resp.VpcAttachment.Attachment.CreatedAt != nil {
			f0.CreatedAt = &metav1.Time{*resp.VpcAttachment.Attachment.CreatedAt}
		}
		if resp.VpcAttachment.Attachment.EdgeLocation != nil {
			f0.EdgeLocation = resp.VpcAttachment.Attachment.EdgeLocation
		}
		if resp.VpcAttachment.Attachment.EdgeLocations != nil {
			f0.EdgeLocations = aws.StringSlice(resp.VpcAttachment.Attachment.EdgeLocations)
		}
		if resp.VpcAttachment.Attachment.LastModificationErrors != nil {
			f0f8 := []*svcapitypes.AttachmentError{}
			for _, f0f8iter := range resp.VpcAttachment.Attachment.LastModificationErrors {
				f0f8elem := &svcapitypes.AttachmentError{}
				if f0f8iter.Code != "" {
					f0f8elem.Code = aws.String(string(f0f8iter.Code))
				}
				if f0f8iter.Message != nil {
					f0f8elem.Message = f0f8iter.Message
				}
				if f0f8iter.RequestId != nil {
					f0f8elem.RequestID = f0f8iter.RequestId
				}
				if f0f8iter.ResourceArn != nil {
					f0f8elem.ResourceARN = f0f8iter.ResourceArn
				}
				f0f8 = append(f0f8, f0f8elem)
			}
			f0.LastModificationErrors = f0f8
		}
		if resp.VpcAttachment.Attachment.NetworkFunctionGroupName != nil {
			f0.NetworkFunctionGroupName = resp.VpcAttachment.Attachment.NetworkFunctionGroupName
		}
		if resp.VpcAttachment.Attachment.OwnerAccountId != nil {
			f0.OwnerAccountID = resp.VpcAttachment.Attachment.OwnerAccountId
		}
		if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange != nil {
			f0f11 := &svcapitypes.ProposedNetworkFunctionGroupChange{}
			if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.AttachmentPolicyRuleNumber != nil {
				attachmentPolicyRuleNumberCopy := int64(*resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.AttachmentPolicyRuleNumber)
				f0f11.AttachmentPolicyRuleNumber = &attachmentPolicyRuleNumberCopy
			}
			if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.NetworkFunctionGroupName != nil {
				f0f11.NetworkFunctionGroupName = resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.NetworkFunctionGroupName
			}
			if resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.Tags != nil {
				f0f11f2 := []*svcapitypes.Tag{}
				for _, f0f11f2iter := range resp.VpcAttachment.Attachment.ProposedNetworkFunctionGroupChange.Tags {
					f0f11f2elem := &svcapitypes.Tag{}
					if f0f11f2iter.Key != nil {
						f0f11f2elem.Key = f0f11f2iter.Key
					}
					if f0f11f2iter.Value != nil {
						f0f11f2elem.Value = f0f11f2iter.Value
					}
					f0f11f2 = append(f0f11f2, f0f11f2elem)
				}
				f0f11.Tags = f0f11f2
			}
			f0.ProposedNetworkFunctionGroupChange = f0f11
		}
		if resp.VpcAttachment.Attachment.ProposedSegmentChange != nil {
			f0f12 := &svcapitypes.ProposedSegmentChange{}
			if resp.VpcAttachment.Attachment.ProposedSegmentChange.AttachmentPolicyRuleNumber != nil {
				attachmentPolicyRuleNumberCopy := int64(*resp.VpcAttachment.Attachment.ProposedSegmentChange.AttachmentPolicyRuleNumber)
				f0f12.AttachmentPolicyRuleNumber = &attachmentPolicyRuleNumberCopy
			}
			if resp.VpcAttachment.Attachment.ProposedSegmentChange.SegmentName != nil {
				f0f12.SegmentName = resp.VpcAttachment.Attachment.ProposedSegmentChange.SegmentName
			}
			if resp.VpcAttachment.Attachment.ProposedSegmentChange.Tags != nil {
				f0f12f2 := []*svcapitypes.Tag{}
				for _, f0f12f2iter := range resp.VpcAttachment.Attachment.ProposedSegmentChange.Tags {
					f0f12f2elem := &svcapitypes.Tag{}
					if f0f12f2iter.Key != nil {
						f0f12f2elem.Key = f0f12f2iter.Key
					}
					if f0f12f2iter.Value != nil {
						f0f12f2elem.Value = f0f12f2iter.Value
					}
					f0f12f2 = append(f0f12f2, f0f12f2elem)
				}
				f0f12.Tags = f0f12f2
			}
			f0.ProposedSegmentChange = f0f12
		}
		if resp.VpcAttachment.Attachment.ResourceArn != nil {
			f0.ResourceARN = resp.VpcAttachment.Attachment.ResourceArn
		}
		if resp.VpcAttachment.Attachment.SegmentName != nil {
			f0.SegmentName = resp.VpcAttachment.Attachment.SegmentName
		}
		if resp.VpcAttachment.Attachment.State != "" {
			f0.State = aws.String(string(resp.VpcAttachment.Attachment.State))
		}
		if resp.VpcAttachment.Attachment.Tags != nil {
			f0f16 := []*svcapitypes.Tag{}
			for _, f0f16iter := range resp.VpcAttachment.Attachment.Tags {
				f0f16elem := &svcapitypes.Tag{}
				if f0f16iter.Key != nil {
					f0f16elem.Key = f0f16iter.Key
				}
				if f0f16iter.Value != nil {
					f0f16elem.Value = f0f16iter.Value
				}
				f0f16 = append(f0f16, f0f16elem)
			}
			f0.Tags = f0f16
		}
		if resp.VpcAttachment.Attachment.UpdatedAt != nil {
			f0.UpdatedAt = &metav1.Time{*resp.VpcAttachment.Attachment.UpdatedAt}
		}
		ko.Status.Attachment = f0
	} else {
		ko.Status.Attachment = nil
	}
	if resp.VpcAttachment.Options != nil {
		f1 := &svcapitypes.VPCOptions{}
		f1.ApplianceModeSupport = resp.VpcAttachment.Options.ApplianceModeSupport
		f1.DNSSupport = resp.VpcAttachment.Options.DnsSupport
		f1.IPv6Support = resp.VpcAttachment.Options.Ipv6Support
		f1.SecurityGroupReferencingSupport = resp.VpcAttachment.Options.SecurityGroupReferencingSupport
		ko.Spec.Options = f1
	} else {
		ko.Spec.Options = nil
	}
	if resp.VpcAttachment.SubnetArns != nil {
		ko.Spec.SubnetARNs = aws.StringSlice(resp.VpcAttachment.SubnetArns)
	} else {
		ko.Spec.SubnetARNs = nil
	}

	rm.setStatusDefaults(ko)
	rm.syncTopLevelStatus(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateVpcAttachmentInput, error) {
	res := &svcsdk.UpdateVpcAttachmentInput{}

	if r.ko.Status.AttachmentID != nil {
		res.AttachmentId = r.ko.Status.AttachmentID
	}
	if r.ko.Spec.Options != nil {
		f2 := &svcsdktypes.VpcOptions{}
		if r.ko.Spec.Options.ApplianceModeSupport != nil {
			f2.ApplianceModeSupport = r.ko.Spec.Options.ApplianceModeSupport
		}
		if r.ko.Spec.Options.DNSSupport != nil {
			f2.DnsSupport = r.ko.Spec.Options.DNSSupport
		}
		if r.ko.Spec.Options.IPv6Support != nil {
			f2.Ipv6Support = r.ko.Spec.Options.IPv6Support
		}
		if r.ko.Spec.Options.SecurityGroupReferencingSupport != nil {
			f2.SecurityGroupReferencingSupport = r.ko.Spec.Options.SecurityGroupReferencingSupport
		}
		res.Options = f2
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	return rm.customDeleteVpcAttachment(ctx, r)
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.VPCAttachment,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"AccessDeniedException":
		return true
	default:
		return false
	}
}
