apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/networkmanager.services.k8s.aws_connectattachments.yaml
  - bases/networkmanager.services.k8s.aws_connectpeers.yaml
  - bases/networkmanager.services.k8s.aws_corenetworks.yaml
  - bases/networkmanager.services.k8s.aws_corenetworkpolicies.yaml
  - bases/networkmanager.services.k8s.aws_globalnetworks.yaml
  - bases/networkmanager.services.k8s.aws_sitetositevpnattachments.yaml
  - bases/networkmanager.services.k8s.aws_vpcattachments.yaml
