// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package core_network_policy

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AutoExecute, b.ko.Spec.AutoExecute) {
		delta.Add("Spec.AutoExecute", a.ko.Spec.AutoExecute, b.ko.Spec.AutoExecute)
	} else if a.ko.Spec.AutoExecute != nil && b.ko.Spec.AutoExecute != nil {
		if *a.ko.Spec.AutoExecute != *b.ko.Spec.AutoExecute {
			delta.Add("Spec.AutoExecute", a.ko.Spec.AutoExecute, b.ko.Spec.AutoExecute)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ClientToken, b.ko.Spec.ClientToken) {
		delta.Add("Spec.ClientToken", a.ko.Spec.ClientToken, b.ko.Spec.ClientToken)
	} else if a.ko.Spec.ClientToken != nil && b.ko.Spec.ClientToken != nil {
		if *a.ko.Spec.ClientToken != *b.ko.Spec.ClientToken {
			delta.Add("Spec.ClientToken", a.ko.Spec.ClientToken, b.ko.Spec.ClientToken)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CoreNetworkID, b.ko.Spec.CoreNetworkID) {
		delta.Add("Spec.CoreNetworkID", a.ko.Spec.CoreNetworkID, b.ko.Spec.CoreNetworkID)
	} else if a.ko.Spec.CoreNetworkID != nil && b.ko.Spec.CoreNetworkID != nil {
		if *a.ko.Spec.CoreNetworkID != *b.ko.Spec.CoreNetworkID {
			delta.Add("Spec.CoreNetworkID", a.ko.Spec.CoreNetworkID, b.ko.Spec.CoreNetworkID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LatestVersionID, b.ko.Spec.LatestVersionID) {
		delta.Add("Spec.LatestVersionID", a.ko.Spec.LatestVersionID, b.ko.Spec.LatestVersionID)
	} else if a.ko.Spec.LatestVersionID != nil && b.ko.Spec.LatestVersionID != nil {
		if *a.ko.Spec.LatestVersionID != *b.ko.Spec.LatestVersionID {
			delta.Add("Spec.LatestVersionID", a.ko.Spec.LatestVersionID, b.ko.Spec.LatestVersionID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PolicyDocument, b.ko.Spec.PolicyDocument) {
		delta.Add("Spec.PolicyDocument", a.ko.Spec.PolicyDocument, b.ko.Spec.PolicyDocument)
	} else if a.ko.Spec.PolicyDocument != nil && b.ko.Spec.PolicyDocument != nil {
		if *a.ko.Spec.PolicyDocument != *b.ko.Spec.PolicyDocument {
			delta.Add("Spec.PolicyDocument", a.ko.Spec.PolicyDocument, b.ko.Spec.PolicyDocument)
		}
	}

	return delta
}
