// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package core_network_policy

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/networkmanager"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/networkmanager/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/networkmanager-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.CoreNetworkPolicy{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetCoreNetworkPolicyOutput
	resp, err = rm.sdkapi.GetCoreNetworkPolicy(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetCoreNetworkPolicy", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.CoreNetworkPolicy.Alias != "" {
		ko.Status.Alias = aws.String(string(resp.CoreNetworkPolicy.Alias))
	} else {
		ko.Status.Alias = nil
	}
	if resp.CoreNetworkPolicy.ChangeSetState != "" {
		ko.Status.ChangeSetState = aws.String(string(resp.CoreNetworkPolicy.ChangeSetState))
	} else {
		ko.Status.ChangeSetState = nil
	}
	if resp.CoreNetworkPolicy.CoreNetworkId != nil {
		ko.Spec.CoreNetworkID = resp.CoreNetworkPolicy.CoreNetworkId
	} else {
		ko.Spec.CoreNetworkID = nil
	}
	if resp.CoreNetworkPolicy.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CoreNetworkPolicy.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.CoreNetworkPolicy.Description != nil {
		ko.Spec.Description = resp.CoreNetworkPolicy.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.CoreNetworkPolicy.PolicyDocument != nil {
		ko.Spec.PolicyDocument = resp.CoreNetworkPolicy.PolicyDocument
	} else {
		ko.Spec.PolicyDocument = nil
	}
	if resp.CoreNetworkPolicy.PolicyErrors != nil {
		f6 := []*svcapitypes.CoreNetworkPolicyError{}
		for _, f6iter := range resp.CoreNetworkPolicy.PolicyErrors {
			f6elem := &svcapitypes.CoreNetworkPolicyError{}
			if f6iter.ErrorCode != nil {
				f6elem.ErrorCode = f6iter.ErrorCode
			}
			if f6iter.Message != nil {
				f6elem.Message = f6iter.Message
			}
			if f6iter.Path != nil {
				f6elem.Path = f6iter.Path
			}
			f6 = append(f6, f6elem)
		}
		ko.Status.PolicyErrors = f6
	} else {
		ko.Status.PolicyErrors = nil
	}
	if resp.CoreNetworkPolicy.PolicyVersionId != nil {
		policyVersionIDCopy := int64(*resp.CoreNetworkPolicy.PolicyVersionId)
		ko.Status.PolicyVersionID = &policyVersionIDCopy
	} else {
		ko.Status.PolicyVersionID = nil
	}

	rm.setStatusDefaults(ko)
	if err = rm.checkChangeSetStateOnRead(ctx, ko); err != nil {
		return &resource{ko}, err
	}
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.CoreNetworkID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetCoreNetworkPolicyInput, error) {
	res := &svcsdk.GetCoreNetworkPolicyInput{}

	if r.ko.Status.Alias != nil {
		res.Alias = svcsdktypes.CoreNetworkPolicyAlias(*r.ko.Status.Alias)
	}
	if r.ko.Spec.CoreNetworkID != nil {
		res.CoreNetworkId = r.ko.Spec.CoreNetworkID
	}
	if r.ko.Status.PolicyVersionID != nil {
		policyVersionIDCopy0 := *r.ko.Status.PolicyVersionID
		if policyVersionIDCopy0 > math.MaxInt32 || policyVersionIDCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field PolicyVersionId is of type int32")
		}
		policyVersionIDCopy := int32(policyVersionIDCopy0)
		res.PolicyVersionId = &policyVersionIDCopy
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.PutCoreNetworkPolicyOutput
	_ = resp
	resp, err = rm.sdkapi.PutCoreNetworkPolicy(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "PutCoreNetworkPolicy", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.CoreNetworkPolicy.Alias != "" {
		ko.Status.Alias = aws.String(string(resp.CoreNetworkPolicy.Alias))
	} else {
		ko.Status.Alias = nil
	}
	if resp.CoreNetworkPolicy.ChangeSetState != "" {
		ko.Status.ChangeSetState = aws.String(string(resp.CoreNetworkPolicy.ChangeSetState))
	} else {
		ko.Status.ChangeSetState = nil
	}
	if resp.CoreNetworkPolicy.CoreNetworkId != nil {
		ko.Spec.CoreNetworkID = resp.CoreNetworkPolicy.CoreNetworkId
	} else {
		ko.Spec.CoreNetworkID = nil
	}
	if resp.CoreNetworkPolicy.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CoreNetworkPolicy.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.CoreNetworkPolicy.Description != nil {
		ko.Spec.Description = resp.CoreNetworkPolicy.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.CoreNetworkPolicy.PolicyDocument != nil {
		ko.Spec.PolicyDocument = resp.CoreNetworkPolicy.PolicyDocument
	} else {
		ko.Spec.PolicyDocument = nil
	}
	if resp.CoreNetworkPolicy.PolicyErrors != nil {
		f6 := []*svcapitypes.CoreNetworkPolicyError{}
		for _, f6iter := range resp.CoreNetworkPolicy.PolicyErrors {
			f6elem := &svcapitypes.CoreNetworkPolicyError{}
			if f6iter.ErrorCode != nil {
				f6elem.ErrorCode = f6iter.ErrorCode
			}
			if f6iter.Message != nil {
				f6elem.Message = f6iter.Message
			}
			if f6iter.Path != nil {
				f6elem.Path = f6iter.Path
			}
			f6 = append(f6, f6elem)
		}
		ko.Status.PolicyErrors = f6
	} else {
		ko.Status.PolicyErrors = nil
	}
	if resp.CoreNetworkPolicy.PolicyVersionId != nil {
		policyVersionIDCopy := int64(*resp.CoreNetworkPolicy.PolicyVersionId)
		ko.Status.PolicyVersionID = &policyVersionIDCopy
	} else {
		ko.Status.PolicyVersionID = nil
	}

	rm.setStatusDefaults(ko)
	if err = rm.handleChangeSetWorkflow(ctx, ko); err != nil {
		return &resource{ko}, err
	}
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.PutCoreNetworkPolicyInput, error) {
	res := &svcsdk.PutCoreNetworkPolicyInput{}

	if r.ko.Spec.ClientToken != nil {
		res.ClientToken = r.ko.Spec.ClientToken
	}
	if r.ko.Spec.CoreNetworkID != nil {
		res.CoreNetworkId = r.ko.Spec.CoreNetworkID
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.LatestVersionID != nil {
		latestVersionIDCopy0 := *r.ko.Spec.LatestVersionID
		if latestVersionIDCopy0 > math.MaxInt32 || latestVersionIDCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field LatestVersionId is of type int32")
		}
		latestVersionIDCopy := int32(latestVersionIDCopy0)
		res.LatestVersionId = &latestVersionIDCopy
	}
	if r.ko.Spec.PolicyDocument != nil {
		res.PolicyDocument = r.ko.Spec.PolicyDocument
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateCoreNetworkPolicy(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	// TODO(jaypipes): Figure this out...
	return nil, nil

}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.CoreNetworkPolicy,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"AccessDeniedException":
		return true
	default:
		return false
	}
}
