// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ConnectPeerSpec defines the desired state of ConnectPeer.
//
// Describes a core network Connect peer.
type ConnectPeerSpec struct {

// The Connect peer BGP options. This only applies only when the protocol is
// GRE.
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
BGPOptions *BGPOptions `json:"bgpOptions,omitempty"`
// The ID of the connection attachment.
//
// Regex Pattern: `^attachment-([0-9a-f]{8,17})$`
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
// +kubebuilder:validation:Required
ConnectAttachmentID *string `json:"connectAttachmentID"`
// A Connect peer core network address. This only applies only when the protocol
// is GRE.
//
// Regex Pattern: `^[\s\S]*$`
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
CoreNetworkAddress *string `json:"coreNetworkAddress,omitempty"`
// The inside IP addresses used for BGP peering.
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
InsideCIDRBlocks []*string `json:"insideCIDRBlocks,omitempty"`
// The Connect peer address.
//
// Regex Pattern: `^[\s\S]*$`
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
// +kubebuilder:validation:Required
PeerAddress *string `json:"peerAddress"`
// The subnet ARN for the Connect peer. This only applies only when the protocol
// is NO_ENCAP.
//
// Regex Pattern: `^arn:[^:]{1,63}:ec2:[^:]{0,63}:[^:]{0,63}:subnet\/subnet-[0-9a-f]{8,17}$|^$`
SubnetARN *string `json:"subnetARN,omitempty"`
// The tags associated with the peer request.
Tags []*Tag `json:"tags,omitempty"`
}

// ConnectPeerStatus defines the observed state of ConnectPeer
type ConnectPeerStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The configuration of the Connect peer.
	// +kubebuilder:validation:Optional
	Configuration *ConnectPeerConfiguration `json:"configuration,omitempty"`
	// The ID of the Connect peer.
//
// Regex Pattern: `^connect-peer-([0-9a-f]{8,17})$`
	// +kubebuilder:validation:Optional
	ConnectPeerID *string `json:"connectPeerID,omitempty"`
	// The ID of a core network.
//
// Regex Pattern: `^core-network-([0-9a-f]{8,17})$`
	// +kubebuilder:validation:Optional
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	// The timestamp when the Connect peer was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The Connect peer Regions where edges are located.
//
// Regex Pattern: `^[\s\S]*$`
	// +kubebuilder:validation:Optional
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	// Describes the error associated with the attachment request.
	// +kubebuilder:validation:Optional
	LastModificationErrors []*ConnectPeerError `json:"lastModificationErrors,omitempty"`
	// The state of the Connect peer.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty"`
}

// ConnectPeer is the Schema for the ConnectPeers API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="STATE",type=string,priority=0,JSONPath=`.status.state`
// +kubebuilder:printcolumn:name="CONNECTATTACHMENT",type=string,priority=0,JSONPath=`.spec.connectAttachmentID`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
// +kubebuilder:printcolumn:name="Age",type="date",priority=0,JSONPath=".metadata.creationTimestamp"
type ConnectPeer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec   ConnectPeerSpec   `json:"spec,omitempty"`
	Status ConnectPeerStatus `json:"status,omitempty"`
}

// ConnectPeerList contains a list of ConnectPeer
// +kubebuilder:object:root=true
type ConnectPeerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []ConnectPeer `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ConnectPeer{}, &ConnectPeerList{})
}