// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CoreNetworkPolicySpec defines the desired state of CoreNetworkPolicy.
//
// Describes a core network policy. You can have only one LIVE Core Policy.
type CoreNetworkPolicySpec struct {

AutoExecute *bool `json:"autoExecute,omitempty"`
// The client token associated with the request.
//
// Regex Pattern: `^[\s\S]*$`
ClientToken *string `json:"clientToken,omitempty"`
// The ID of a core network.
//
// Regex Pattern: `^core-network-([0-9a-f]{8,17})$`
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
// +kubebuilder:validation:Required
CoreNetworkID *string `json:"coreNetworkID"`
// a core network policy description.
//
// Regex Pattern: `^[\s\S]*$`
Description *string `json:"description,omitempty"`
// The ID of a core network policy.
LatestVersionID *int64 `json:"latestVersionID,omitempty"`
// +kubebuilder:validation:Required
PolicyDocument *string `json:"policyDocument"`
}

// CoreNetworkPolicyStatus defines the observed state of CoreNetworkPolicy
type CoreNetworkPolicyStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// Whether a core network policy is the current LIVE policy or the most recently
// submitted policy.
	// +kubebuilder:validation:Optional
	Alias *string `json:"alias,omitempty"`
	// The state of a core network policy.
	// +kubebuilder:validation:Optional
	ChangeSetState *string `json:"changeSetState,omitempty"`
	// The timestamp when a core network policy was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// Describes any errors in a core network policy.
	// +kubebuilder:validation:Optional
	PolicyErrors []*CoreNetworkPolicyError `json:"policyErrors,omitempty"`
	// The ID of the policy version.
	// +kubebuilder:validation:Optional
	PolicyVersionID *int64 `json:"policyVersionID,omitempty"`
}

// CoreNetworkPolicy is the Schema for the CoreNetworkPolicies API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="CORENETWORKID",type=string,priority=0,JSONPath=`.spec.coreNetworkID`
// +kubebuilder:printcolumn:name="POLICYVERSION",type=string,priority=0,JSONPath=`.status.policyVersionID`
// +kubebuilder:printcolumn:name="CHANGESETSTATE",type=string,priority=0,JSONPath=`.status.changeSetState`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
// +kubebuilder:printcolumn:name="Age",type="date",priority=0,JSONPath=".metadata.creationTimestamp"
type CoreNetworkPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec   CoreNetworkPolicySpec   `json:"spec,omitempty"`
	Status CoreNetworkPolicyStatus `json:"status,omitempty"`
}

// CoreNetworkPolicyList contains a list of CoreNetworkPolicy
// +kubebuilder:object:root=true
type CoreNetworkPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []CoreNetworkPolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&CoreNetworkPolicy{}, &CoreNetworkPolicyList{})
}