// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GlobalNetworkSpec defines the desired state of GlobalNetwork.
//
// Describes a global network. This is a single private network acting as a
// high-level container for your network objects, including an Amazon Web Services-managed
// Core Network.
type GlobalNetworkSpec struct {

	// A description of the global network.
	//
	// Constraints: Maximum length of 256 characters.
	//
	// Regex Pattern: `^[\s\S]*$`
	Description *string `json:"description,omitempty"`
	// The tags to apply to the resource during creation.
	Tags []*Tag `json:"tags,omitempty"`
}

// GlobalNetworkStatus defines the observed state of GlobalNetwork
type GlobalNetworkStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time that the global network was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The ID of the global network.
	//
	// Regex Pattern: `^[\s\S]*$`
	// +kubebuilder:validation:Optional
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
	// The state of the global network.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty"`
}

// GlobalNetwork is the Schema for the GlobalNetworks API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type GlobalNetwork struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GlobalNetworkSpec   `json:"spec,omitempty"`
	Status            GlobalNetworkStatus `json:"status,omitempty"`
}

// GlobalNetworkList contains a list of GlobalNetwork
// +kubebuilder:object:root=true
type GlobalNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GlobalNetwork `json:"items"`
}

func init() {
	SchemeBuilder.Register(&GlobalNetwork{}, &GlobalNetworkList{})
}
