// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)


// Specifies a location in Amazon Web Services.
type AWSLocation struct {
	SubnetARN *string `json:"subnetARN,omitempty"`
	Zone *string `json:"zone,omitempty"`
}


// Describes a core network attachment.
type Attachment struct {
	AttachmentID *string `json:"attachmentID,omitempty"`
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty"`
	AttachmentType *string `json:"attachmentType,omitempty"`
	CoreNetworkARN *string `json:"coreNetworkARN,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	EdgeLocations []*string `json:"edgeLocations,omitempty"`
	LastModificationErrors []*AttachmentError `json:"lastModificationErrors,omitempty"`
	NetworkFunctionGroupName *string `json:"networkFunctionGroupName,omitempty"`
	OwnerAccountID *string `json:"ownerAccountID,omitempty"`
	// Describes proposed changes to a network function group.
	ProposedNetworkFunctionGroupChange *ProposedNetworkFunctionGroupChange `json:"proposedNetworkFunctionGroupChange,omitempty"`
	// Describes a proposed segment change. In some cases, the segment change must
// first be evaluated and accepted.
	ProposedSegmentChange *ProposedSegmentChange `json:"proposedSegmentChange,omitempty"`
	ResourceARN *string `json:"resourceARN,omitempty"`
	SegmentName *string `json:"segmentName,omitempty"`
	State *string `json:"state,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}


// Describes the error associated with an attachment request.
type AttachmentError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	RequestID *string `json:"requestID,omitempty"`
	ResourceARN *string `json:"resourceARN,omitempty"`
}


// Summary information about routing policy associations for an attachment.
type AttachmentRoutingPolicyAssociationSummary struct {
	AssociatedRoutingPolicies []*string `json:"associatedRoutingPolicies,omitempty"`
	AttachmentID *string `json:"attachmentID,omitempty"`
	PendingRoutingPolicies []*string `json:"pendingRoutingPolicies,omitempty"`
	RoutingPolicyLabel *string `json:"routingPolicyLabel,omitempty"`
}


// Describes the BGP options.
type BGPOptions struct {
	PeerASN *int64 `json:"peerASN,omitempty"`
}


// Describes bandwidth information.
type Bandwidth struct {
	DownloadSpeed *int64 `json:"downloadSpeed,omitempty"`
	UploadSpeed *int64 `json:"uploadSpeed,omitempty"`
}


// Describes a core network Connect attachment options.
type ConnectAttachmentOptions struct {
	Protocol *string `json:"protocol,omitempty"`
}


// Describes a core network Connect attachment.
type ConnectAttachment_SDK struct {
	// Describes a core network attachment.
	Attachment *Attachment `json:"attachment,omitempty"`
	// Describes a core network Connect attachment options.
	Options *ConnectAttachmentOptions `json:"options,omitempty"`
	TransportAttachmentID *string `json:"transportAttachmentID,omitempty"`
}


// Describes a core network Connect peer association.
type ConnectPeerAssociation struct {
	ConnectPeerID *string `json:"connectPeerID,omitempty"`
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
}


// Describes a core network BGP configuration.
type ConnectPeerBGPConfiguration struct {
	CoreNetworkAddress *string `json:"coreNetworkAddress,omitempty"`
	CoreNetworkASN *int64 `json:"coreNetworkASN,omitempty"`
	PeerAddress *string `json:"peerAddress,omitempty"`
	PeerASN *int64 `json:"peerASN,omitempty"`
}


// Describes a core network Connect peer configuration.
type ConnectPeerConfiguration struct {
	BGPConfigurations []*ConnectPeerBGPConfiguration `json:"bgpConfigurations,omitempty"`
	CoreNetworkAddress *string `json:"coreNetworkAddress,omitempty"`
	InsideCIDRBlocks []*string `json:"insideCIDRBlocks,omitempty"`
	PeerAddress *string `json:"peerAddress,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
}


// Describes an error associated with a Connect peer request
type ConnectPeerError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	RequestID *string `json:"requestID,omitempty"`
	ResourceARN *string `json:"resourceARN,omitempty"`
}


// Summary description of a Connect peer.
type ConnectPeerSummary struct {
	ConnectAttachmentID *string `json:"connectAttachmentID,omitempty"`
	ConnectPeerID *string `json:"connectPeerID,omitempty"`
	ConnectPeerState *string `json:"connectPeerState,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	SubnetARN *string `json:"subnetARN,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes a core network Connect peer.
type ConnectPeer_SDK struct {
	// Describes a core network Connect peer configuration.
	Configuration *ConnectPeerConfiguration `json:"configuration,omitempty"`
	ConnectAttachmentID *string `json:"connectAttachmentID,omitempty"`
	ConnectPeerID *string `json:"connectPeerID,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	LastModificationErrors []*ConnectPeerError `json:"lastModificationErrors,omitempty"`
	State *string `json:"state,omitempty"`
	SubnetARN *string `json:"subnetARN,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes a connection.
type Connection struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	Description *string `json:"description,omitempty"`
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes connection health.
type ConnectionHealth struct {
	Timestamp *metav1.Time `json:"timestamp,omitempty"`
}


// Details describing a core network change.
type CoreNetworkChange struct {
	Identifier *string `json:"identifier,omitempty"`
	IdentifierPath *string `json:"identifierPath,omitempty"`
}


// Describes a core network change event. This can be a change to a segment,
// attachment, route, etc.
type CoreNetworkChangeEvent struct {
	EventTime *metav1.Time `json:"eventTime,omitempty"`
	IdentifierPath *string `json:"identifierPath,omitempty"`
}


// Describes a core network change event.
type CoreNetworkChangeEventValues struct {
	AttachmentID *string `json:"attachmentID,omitempty"`
	CIDR *string `json:"cidr,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	NetworkFunctionGroupName *string `json:"networkFunctionGroupName,omitempty"`
	PeerEdgeLocation *string `json:"peerEdgeLocation,omitempty"`
	SegmentName *string `json:"segmentName,omitempty"`
}


// Describes a core network change.
type CoreNetworkChangeValues struct {
	ASN *int64 `json:"asn,omitempty"`
	AttachmentID *string `json:"attachmentID,omitempty"`
	CIDR *string `json:"cidr,omitempty"`
	DestinationIdentifier *string `json:"destinationIdentifier,omitempty"`
	DNSSupport *bool `json:"dnsSupport,omitempty"`
	EdgeLocations []*string `json:"edgeLocations,omitempty"`
	InsideCIDRBlocks []*string `json:"insideCIDRBlocks,omitempty"`
	NetworkFunctionGroupName *string `json:"networkFunctionGroupName,omitempty"`
	PeerEdgeLocations []*string `json:"peerEdgeLocations,omitempty"`
	RoutingPolicy *string `json:"routingPolicy,omitempty"`
	SecurityGroupReferencingSupport *bool `json:"securityGroupReferencingSupport,omitempty"`
	SegmentName *string `json:"segmentName,omitempty"`
	SharedSegments []*string `json:"sharedSegments,omitempty"`
	VPNECMPSupport *bool `json:"vpnECMPSupport,omitempty"`
}


// Describes a core network edge.
type CoreNetworkEdge struct {
	ASN *int64 `json:"asn,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	InsideCIDRBlocks []*string `json:"insideCIDRBlocks,omitempty"`
}


// Describes a network function group.
type CoreNetworkNetworkFunctionGroup struct {
	EdgeLocations []*string `json:"edgeLocations,omitempty"`
	Name *string `json:"name,omitempty"`
	// Describes the segments associated with the service insertion action.
	Segments *ServiceInsertionSegments `json:"segments,omitempty"`
}


// Describes a core network
type CoreNetworkNetworkFunctionGroupIdentifier struct {
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	NetworkFunctionGroupName *string `json:"networkFunctionGroupName,omitempty"`
}


// Provides details about an error in a core network policy.
type CoreNetworkPolicyError struct {
	ErrorCode *string `json:"errorCode,omitempty"`
	Message *string `json:"message,omitempty"`
	Path *string `json:"path,omitempty"`
}


// Describes a core network policy version.
type CoreNetworkPolicyVersion struct {
	Alias *string `json:"alias,omitempty"`
	ChangeSetState *string `json:"changeSetState,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	Description *string `json:"description,omitempty"`
	PolicyVersionID *int64 `json:"policyVersionID,omitempty"`
}


// Describes a core network policy. You can have only one LIVE Core Policy.
type CoreNetworkPolicy_SDK struct {
	Alias *string `json:"alias,omitempty"`
	ChangeSetState *string `json:"changeSetState,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	Description *string `json:"description,omitempty"`
	PolicyDocument *string `json:"policyDocument,omitempty"`
	PolicyErrors []*CoreNetworkPolicyError `json:"policyErrors,omitempty"`
	PolicyVersionID *int64 `json:"policyVersionID,omitempty"`
}


// Routing information for a core network, including route details and BGP attributes.
type CoreNetworkRoutingInformation struct {
	AsPath []*string `json:"asPath,omitempty"`
	Communities []*string `json:"communities,omitempty"`
	LocalPreference *string `json:"localPreference,omitempty"`
	Med *string `json:"med,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
}


// Describes a core network segment, which are dedicated routes. Only attachments
// within this segment can communicate with each other.
type CoreNetworkSegment struct {
	EdgeLocations []*string `json:"edgeLocations,omitempty"`
	Name *string `json:"name,omitempty"`
	SharedSegments []*string `json:"sharedSegments,omitempty"`
}


// Returns details about a core network edge.
type CoreNetworkSegmentEdgeIdentifier struct {
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	SegmentName *string `json:"segmentName,omitempty"`
}


// Returns summary information about a core network.
type CoreNetworkSummary struct {
	CoreNetworkARN *string `json:"coreNetworkARN,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	Description *string `json:"description,omitempty"`
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
	OwnerAccountID *string `json:"ownerAccountID,omitempty"`
	State *string `json:"state,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes a core network.
type CoreNetwork_SDK struct {
	CoreNetworkARN *string `json:"coreNetworkARN,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	Description *string `json:"description,omitempty"`
	Edges []*CoreNetworkEdge `json:"edges,omitempty"`
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
	NetworkFunctionGroups []*CoreNetworkNetworkFunctionGroup `json:"networkFunctionGroups,omitempty"`
	Segments []*CoreNetworkSegment `json:"segments,omitempty"`
	State *string `json:"state,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes the association between a customer gateway, a device, and a link.
type CustomerGatewayAssociation struct {
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
}


// Describes a device.
type Device struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	Description *string `json:"description,omitempty"`
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
	Model *string `json:"model,omitempty"`
	SerialNumber *string `json:"serialNumber,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
	Type *string `json:"type_,omitempty"`
	Vendor *string `json:"vendor,omitempty"`
}


// Describes a Direct Connect gateway attachment.
type DirectConnectGatewayAttachment struct {
	// Describes a core network attachment.
	Attachment *Attachment `json:"attachment,omitempty"`
}


// Describes the edge that's used for the override.
type EdgeOverride struct {
	UseEdge *string `json:"useEdge,omitempty"`
}


// Describes a global network. This is a single private network acting as a
// high-level container for your network objects, including an Amazon Web Services-managed
// Core Network.
type GlobalNetwork_SDK struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	Description *string `json:"description,omitempty"`
	GlobalNetworkARN *string `json:"globalNetworkARN,omitempty"`
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
	State *string `json:"state,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes a link.
type Link struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	Description *string `json:"description,omitempty"`
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
	Provider *string `json:"provider,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
	Type *string `json:"type_,omitempty"`
}


// Describes the association between a device and a link.
type LinkAssociation struct {
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
}


// Describes a location.
type Location struct {
	Address *string `json:"address,omitempty"`
	Latitude *string `json:"latitude,omitempty"`
	Longitude *string `json:"longitude,omitempty"`
}


// Describes a network function group for service insertion.
type NetworkFunctionGroup struct {
	Name *string `json:"name,omitempty"`
}


// Describes a network resource.
type NetworkResource struct {
	AccountID *string `json:"accountID,omitempty"`
	AWSRegion *string `json:"awsRegion,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	Definition *string `json:"definition,omitempty"`
	DefinitionTimestamp *metav1.Time `json:"definitionTimestamp,omitempty"`
	RegisteredGatewayARN *string `json:"registeredGatewayARN,omitempty"`
	ResourceARN *string `json:"resourceARN,omitempty"`
	ResourceID *string `json:"resourceID,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes a resource count.
type NetworkResourceCount struct {
	Count *int64 `json:"count,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}


// Describes a network resource.
type NetworkResourceSummary struct {
	Definition *string `json:"definition,omitempty"`
	IsMiddlebox *bool `json:"isMiddlebox,omitempty"`
	NameTag *string `json:"nameTag,omitempty"`
	RegisteredGatewayARN *string `json:"registeredGatewayARN,omitempty"`
	ResourceARN *string `json:"resourceARN,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}


// Describes a network route.
type NetworkRoute struct {
	DestinationCIDRBlock *string `json:"destinationCIDRBlock,omitempty"`
	PrefixListID *string `json:"prefixListID,omitempty"`
}


// Describes the destination of a network route.
type NetworkRouteDestination struct {
	CoreNetworkAttachmentID *string `json:"coreNetworkAttachmentID,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	NetworkFunctionGroupName *string `json:"networkFunctionGroupName,omitempty"`
	ResourceID *string `json:"resourceID,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
	SegmentName *string `json:"segmentName,omitempty"`
}


// Describes the telemetry information for a resource.
type NetworkTelemetry struct {
	AccountID *string `json:"accountID,omitempty"`
	Address *string `json:"address,omitempty"`
	AWSRegion *string `json:"awsRegion,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	RegisteredGatewayARN *string `json:"registeredGatewayARN,omitempty"`
	ResourceARN *string `json:"resourceARN,omitempty"`
	ResourceID *string `json:"resourceID,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}


// Describes a path component.
type PathComponent struct {
	DestinationCIDRBlock *string `json:"destinationCIDRBlock,omitempty"`
	Sequence *int64 `json:"sequence,omitempty"`
}


// Describes a peering connection.
type Peering struct {
	CoreNetworkARN *string `json:"coreNetworkARN,omitempty"`
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	OwnerAccountID *string `json:"ownerAccountID,omitempty"`
	ResourceARN *string `json:"resourceARN,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes an error associated with a peering request.
type PeeringError struct {
	Message *string `json:"message,omitempty"`
	RequestID *string `json:"requestID,omitempty"`
	ResourceARN *string `json:"resourceARN,omitempty"`
}


// Describes additional information about missing permissions.
type PermissionsErrorContext struct {
	MissingPermission *string `json:"missingPermission,omitempty"`
}


// Information about a prefix list association with a core network.
type PrefixListAssociation struct {
	CoreNetworkID *string `json:"coreNetworkID,omitempty"`
	PrefixListAlias *string `json:"prefixListAlias,omitempty"`
}


// Describes proposed changes to a network function group.
type ProposedNetworkFunctionGroupChange struct {
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty"`
	NetworkFunctionGroupName *string `json:"networkFunctionGroupName,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes a proposed segment change. In some cases, the segment change must
// first be evaluated and accepted.
type ProposedSegmentChange struct {
	AttachmentPolicyRuleNumber *int64 `json:"attachmentPolicyRuleNumber,omitempty"`
	SegmentName *string `json:"segmentName,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Describes a resource relationship.
type Relationship struct {
	From *string `json:"from,omitempty"`
	To *string `json:"to,omitempty"`
}


// Describes a route analysis.
type RouteAnalysis struct {
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
	IncludeReturnPath *bool `json:"includeReturnPath,omitempty"`
	OwnerAccountID *string `json:"ownerAccountID,omitempty"`
	RouteAnalysisID *string `json:"routeAnalysisID,omitempty"`
	StartTimestamp *metav1.Time `json:"startTimestamp,omitempty"`
	UseMiddleboxes *bool `json:"useMiddleboxes,omitempty"`
}


// Describes a source or a destination.
type RouteAnalysisEndpointOptions struct {
	IPAddress *string `json:"ipAddress,omitempty"`
}


// Describes a source or a destination.
type RouteAnalysisEndpointOptionsSpecification struct {
	IPAddress *string `json:"ipAddress,omitempty"`
}


// Information about the next hop for a route in the core network.
type RoutingInformationNextHop struct {
	CoreNetworkAttachmentID *string `json:"coreNetworkAttachmentID,omitempty"`
	EdgeLocation *string `json:"edgeLocation,omitempty"`
	IPAddress *string `json:"ipAddress,omitempty"`
	ResourceID *string `json:"resourceID,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
	SegmentName *string `json:"segmentName,omitempty"`
}


// Information about a routing policy association.
type RoutingPolicyAssociationDetail struct {
	RoutingPolicyNames []*string `json:"routingPolicyNames,omitempty"`
	SharedSegments []*string `json:"sharedSegments,omitempty"`
}


// Describes the segments associated with the service insertion action.
type ServiceInsertionSegments struct {
	SendTo []*string `json:"sendTo,omitempty"`
	SendVia []*string `json:"sendVia,omitempty"`
}


// Describes a site.
type Site struct {
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	Description *string `json:"description,omitempty"`
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}


// Creates a site-to-site VPN attachment.
type SiteToSiteVPNAttachment_SDK struct {
	// Describes a core network attachment.
	Attachment *Attachment `json:"attachment,omitempty"`
	VPNConnectionARN *string `json:"vpnConnectionARN,omitempty"`
}


// Describes a tag.
type Tag struct {
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}


// Describes a transit gateway Connect peer association.
type TransitGatewayConnectPeerAssociation struct {
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
}


// Describes the registration of a transit gateway to a global network.
type TransitGatewayRegistration struct {
	GlobalNetworkID *string `json:"globalNetworkID,omitempty"`
}


// Describes the status of a transit gateway registration.
type TransitGatewayRegistrationStateReason struct {
	Message *string `json:"message,omitempty"`
}


// Describes a transit gateway route table attachment.
type TransitGatewayRouteTableAttachment struct {
	// Describes a core network attachment.
	Attachment *Attachment `json:"attachment,omitempty"`
}


// Describes a VPC attachment.
type VPCAttachment_SDK struct {
	// Describes a core network attachment.
	Attachment *Attachment `json:"attachment,omitempty"`
	// Describes the VPC options.
	Options *VPCOptions `json:"options,omitempty"`
	SubnetARNs []*string `json:"subnetARNs,omitempty"`
}


// Describes the VPC options.
type VPCOptions struct {
	ApplianceModeSupport *bool `json:"applianceModeSupport,omitempty"`
	DNSSupport *bool `json:"dnsSupport,omitempty"`
	IPv6Support *bool `json:"ipv6Support,omitempty"`
	SecurityGroupReferencingSupport *bool `json:"securityGroupReferencingSupport,omitempty"`
}


// Describes a validation exception for a field.
type ValidationExceptionField struct {
	Message *string `json:"message,omitempty"`
	Name *string `json:"name,omitempty"`
}