// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VpcAttachmentSpec defines the desired state of VpcAttachment.
//
// Describes a VPC attachment.
type VPCAttachmentSpec struct {

// The ID of a core network for the VPC attachment.
//
// Regex Pattern: `^core-network-([0-9a-f]{8,17})$`
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
// +kubebuilder:validation:Required
CoreNetworkID *string `json:"coreNetworkID"`
// Options for the VPC attachment.
Options *VPCOptions `json:"options,omitempty"`
// The routing policy label to apply to the VPC attachment for traffic routing
// decisions.
//
// Regex Pattern: `^[\s\S]*$`
RoutingPolicyLabel *string `json:"routingPolicyLabel,omitempty"`
// The subnet ARN of the VPC attachment.
// +kubebuilder:validation:Required
SubnetARNs []*string `json:"subnetARNs"`
// The key-value tags associated with the request.
Tags []*Tag `json:"tags,omitempty"`
// The ARN of the VPC.
//
// Regex Pattern: `^arn:[^:]{1,63}:ec2:[^:]{0,63}:[^:]{0,63}:vpc\/vpc-[0-9a-f]{8,17}$`
// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
// +kubebuilder:validation:Required
VPCARN *string `json:"vpcARN"`
}

// VPCAttachmentStatus defines the observed state of VPCAttachment
type VPCAttachmentStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// Provides details about the VPC attachment.
	// +kubebuilder:validation:Optional
	Attachment *Attachment `json:"attachment,omitempty"`
	// The ID of the attachment.
//
// Regex Pattern: `^attachment-([0-9a-f]{8,17})$`
	// +kubebuilder:validation:Optional
	AttachmentID *string `json:"attachmentID,omitempty"`
	// The state of the attachment.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty"`
}

// VPCAttachment is the Schema for the VPCAttachments API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ATTACHMENTID",type=string,priority=0,JSONPath=`.status.attachmentID`
// +kubebuilder:printcolumn:name="CORENETWORK",type=string,priority=1,JSONPath=`.spec.coreNetworkID`
// +kubebuilder:printcolumn:name="STATE",type=string,priority=0,JSONPath=`.status.state`
type VPCAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec   VPCAttachmentSpec   `json:"spec,omitempty"`
	Status VPCAttachmentStatus `json:"status,omitempty"`
}

// VPCAttachmentList contains a list of VPCAttachment
// +kubebuilder:object:root=true
type VPCAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []VPCAttachment `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VPCAttachment{}, &VPCAttachmentList{})
}