//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSLocation) DeepCopyInto(out *AWSLocation) {
	*out = *in
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSLocation.
func (in *AWSLocation) DeepCopy() *AWSLocation {
	if in == nil {
		return nil
	}
	out := new(AWSLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Attachment) DeepCopyInto(out *Attachment) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.SegmentName != nil {
		in, out := &in.SegmentName, &out.SegmentName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Attachment.
func (in *Attachment) DeepCopy() *Attachment {
	if in == nil {
		return nil
	}
	out := new(Attachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachmentRoutingPolicyAssociationSummary) DeepCopyInto(out *AttachmentRoutingPolicyAssociationSummary) {
	*out = *in
	if in.RoutingPolicyLabel != nil {
		in, out := &in.RoutingPolicyLabel, &out.RoutingPolicyLabel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachmentRoutingPolicyAssociationSummary.
func (in *AttachmentRoutingPolicyAssociationSummary) DeepCopy() *AttachmentRoutingPolicyAssociationSummary {
	if in == nil {
		return nil
	}
	out := new(AttachmentRoutingPolicyAssociationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectPeer) DeepCopyInto(out *ConnectPeer) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectPeer.
func (in *ConnectPeer) DeepCopy() *ConnectPeer {
	if in == nil {
		return nil
	}
	out := new(ConnectPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectPeerAssociation) DeepCopyInto(out *ConnectPeerAssociation) {
	*out = *in
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectPeerAssociation.
func (in *ConnectPeerAssociation) DeepCopy() *ConnectPeerAssociation {
	if in == nil {
		return nil
	}
	out := new(ConnectPeerAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectPeerSummary) DeepCopyInto(out *ConnectPeerSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectPeerSummary.
func (in *ConnectPeerSummary) DeepCopy() *ConnectPeerSummary {
	if in == nil {
		return nil
	}
	out := new(ConnectPeerSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionHealth) DeepCopyInto(out *ConnectionHealth) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionHealth.
func (in *ConnectionHealth) DeepCopy() *ConnectionHealth {
	if in == nil {
		return nil
	}
	out := new(ConnectionHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetwork) DeepCopyInto(out *CoreNetwork) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetwork.
func (in *CoreNetwork) DeepCopy() *CoreNetwork {
	if in == nil {
		return nil
	}
	out := new(CoreNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkChange) DeepCopyInto(out *CoreNetworkChange) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.IdentifierPath != nil {
		in, out := &in.IdentifierPath, &out.IdentifierPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkChange.
func (in *CoreNetworkChange) DeepCopy() *CoreNetworkChange {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkChangeEvent) DeepCopyInto(out *CoreNetworkChangeEvent) {
	*out = *in
	if in.EventTime != nil {
		in, out := &in.EventTime, &out.EventTime
		*out = (*in).DeepCopy()
	}
	if in.IdentifierPath != nil {
		in, out := &in.IdentifierPath, &out.IdentifierPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkChangeEvent.
func (in *CoreNetworkChangeEvent) DeepCopy() *CoreNetworkChangeEvent {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkChangeEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkChangeEventValues) DeepCopyInto(out *CoreNetworkChangeEventValues) {
	*out = *in
	if in.CIDR != nil {
		in, out := &in.CIDR, &out.CIDR
		*out = new(string)
		**out = **in
	}
	if in.NetworkFunctionGroupName != nil {
		in, out := &in.NetworkFunctionGroupName, &out.NetworkFunctionGroupName
		*out = new(string)
		**out = **in
	}
	if in.SegmentName != nil {
		in, out := &in.SegmentName, &out.SegmentName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkChangeEventValues.
func (in *CoreNetworkChangeEventValues) DeepCopy() *CoreNetworkChangeEventValues {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkChangeEventValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkChangeValues) DeepCopyInto(out *CoreNetworkChangeValues) {
	*out = *in
	if in.AttachmentID != nil {
		in, out := &in.AttachmentID, &out.AttachmentID
		*out = new(string)
		**out = **in
	}
	if in.CIDR != nil {
		in, out := &in.CIDR, &out.CIDR
		*out = new(string)
		**out = **in
	}
	if in.DestinationIdentifier != nil {
		in, out := &in.DestinationIdentifier, &out.DestinationIdentifier
		*out = new(string)
		**out = **in
	}
	if in.NetworkFunctionGroupName != nil {
		in, out := &in.NetworkFunctionGroupName, &out.NetworkFunctionGroupName
		*out = new(string)
		**out = **in
	}
	if in.SegmentName != nil {
		in, out := &in.SegmentName, &out.SegmentName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkChangeValues.
func (in *CoreNetworkChangeValues) DeepCopy() *CoreNetworkChangeValues {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkChangeValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkNetworkFunctionGroup) DeepCopyInto(out *CoreNetworkNetworkFunctionGroup) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkNetworkFunctionGroup.
func (in *CoreNetworkNetworkFunctionGroup) DeepCopy() *CoreNetworkNetworkFunctionGroup {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkNetworkFunctionGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkNetworkFunctionGroupIdentifier) DeepCopyInto(out *CoreNetworkNetworkFunctionGroupIdentifier) {
	*out = *in
	if in.NetworkFunctionGroupName != nil {
		in, out := &in.NetworkFunctionGroupName, &out.NetworkFunctionGroupName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkNetworkFunctionGroupIdentifier.
func (in *CoreNetworkNetworkFunctionGroupIdentifier) DeepCopy() *CoreNetworkNetworkFunctionGroupIdentifier {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkNetworkFunctionGroupIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkPolicy) DeepCopyInto(out *CoreNetworkPolicy) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkPolicy.
func (in *CoreNetworkPolicy) DeepCopy() *CoreNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkPolicyVersion) DeepCopyInto(out *CoreNetworkPolicyVersion) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkPolicyVersion.
func (in *CoreNetworkPolicyVersion) DeepCopy() *CoreNetworkPolicyVersion {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkPolicyVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkRoutingInformation) DeepCopyInto(out *CoreNetworkRoutingInformation) {
	*out = *in
	if in.LocalPreference != nil {
		in, out := &in.LocalPreference, &out.LocalPreference
		*out = new(string)
		**out = **in
	}
	if in.Med != nil {
		in, out := &in.Med, &out.Med
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkRoutingInformation.
func (in *CoreNetworkRoutingInformation) DeepCopy() *CoreNetworkRoutingInformation {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkRoutingInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkSegment) DeepCopyInto(out *CoreNetworkSegment) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkSegment.
func (in *CoreNetworkSegment) DeepCopy() *CoreNetworkSegment {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkSegment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkSegmentEdgeIdentifier) DeepCopyInto(out *CoreNetworkSegmentEdgeIdentifier) {
	*out = *in
	if in.SegmentName != nil {
		in, out := &in.SegmentName, &out.SegmentName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkSegmentEdgeIdentifier.
func (in *CoreNetworkSegmentEdgeIdentifier) DeepCopy() *CoreNetworkSegmentEdgeIdentifier {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkSegmentEdgeIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreNetworkSummary) DeepCopyInto(out *CoreNetworkSummary) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreNetworkSummary.
func (in *CoreNetworkSummary) DeepCopy() *CoreNetworkSummary {
	if in == nil {
		return nil
	}
	out := new(CoreNetworkSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerGatewayAssociation) DeepCopyInto(out *CustomerGatewayAssociation) {
	*out = *in
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerGatewayAssociation.
func (in *CustomerGatewayAssociation) DeepCopy() *CustomerGatewayAssociation {
	if in == nil {
		return nil
	}
	out := new(CustomerGatewayAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Device) DeepCopyInto(out *Device) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.SerialNumber != nil {
		in, out := &in.SerialNumber, &out.SerialNumber
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Vendor != nil {
		in, out := &in.Vendor, &out.Vendor
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Device.
func (in *Device) DeepCopy() *Device {
	if in == nil {
		return nil
	}
	out := new(Device)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeOverride) DeepCopyInto(out *EdgeOverride) {
	*out = *in
	if in.UseEdge != nil {
		in, out := &in.UseEdge, &out.UseEdge
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeOverride.
func (in *EdgeOverride) DeepCopy() *EdgeOverride {
	if in == nil {
		return nil
	}
	out := new(EdgeOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalNetwork) DeepCopyInto(out *GlobalNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalNetwork.
func (in *GlobalNetwork) DeepCopy() *GlobalNetwork {
	if in == nil {
		return nil
	}
	out := new(GlobalNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalNetworkList) DeepCopyInto(out *GlobalNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalNetworkList.
func (in *GlobalNetworkList) DeepCopy() *GlobalNetworkList {
	if in == nil {
		return nil
	}
	out := new(GlobalNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalNetworkSpec) DeepCopyInto(out *GlobalNetworkSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalNetworkSpec.
func (in *GlobalNetworkSpec) DeepCopy() *GlobalNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalNetworkStatus) DeepCopyInto(out *GlobalNetworkStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalNetworkStatus.
func (in *GlobalNetworkStatus) DeepCopy() *GlobalNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(GlobalNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalNetwork_SDK) DeepCopyInto(out *GlobalNetwork_SDK) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalNetworkARN != nil {
		in, out := &in.GlobalNetworkARN, &out.GlobalNetworkARN
		*out = new(string)
		**out = **in
	}
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalNetwork_SDK.
func (in *GlobalNetwork_SDK) DeepCopy() *GlobalNetwork_SDK {
	if in == nil {
		return nil
	}
	out := new(GlobalNetwork_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Link) DeepCopyInto(out *Link) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Link.
func (in *Link) DeepCopy() *Link {
	if in == nil {
		return nil
	}
	out := new(Link)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinkAssociation) DeepCopyInto(out *LinkAssociation) {
	*out = *in
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinkAssociation.
func (in *LinkAssociation) DeepCopy() *LinkAssociation {
	if in == nil {
		return nil
	}
	out := new(LinkAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Location) DeepCopyInto(out *Location) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Latitude != nil {
		in, out := &in.Latitude, &out.Latitude
		*out = new(string)
		**out = **in
	}
	if in.Longitude != nil {
		in, out := &in.Longitude, &out.Longitude
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Location.
func (in *Location) DeepCopy() *Location {
	if in == nil {
		return nil
	}
	out := new(Location)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkFunctionGroup) DeepCopyInto(out *NetworkFunctionGroup) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkFunctionGroup.
func (in *NetworkFunctionGroup) DeepCopy() *NetworkFunctionGroup {
	if in == nil {
		return nil
	}
	out := new(NetworkFunctionGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkResource) DeepCopyInto(out *NetworkResource) {
	*out = *in
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = new(string)
		**out = **in
	}
	if in.DefinitionTimestamp != nil {
		in, out := &in.DefinitionTimestamp, &out.DefinitionTimestamp
		*out = (*in).DeepCopy()
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkResource.
func (in *NetworkResource) DeepCopy() *NetworkResource {
	if in == nil {
		return nil
	}
	out := new(NetworkResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkResourceCount) DeepCopyInto(out *NetworkResourceCount) {
	*out = *in
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkResourceCount.
func (in *NetworkResourceCount) DeepCopy() *NetworkResourceCount {
	if in == nil {
		return nil
	}
	out := new(NetworkResourceCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkResourceSummary) DeepCopyInto(out *NetworkResourceSummary) {
	*out = *in
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = new(string)
		**out = **in
	}
	if in.NameTag != nil {
		in, out := &in.NameTag, &out.NameTag
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkResourceSummary.
func (in *NetworkResourceSummary) DeepCopy() *NetworkResourceSummary {
	if in == nil {
		return nil
	}
	out := new(NetworkResourceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRoute) DeepCopyInto(out *NetworkRoute) {
	*out = *in
	if in.DestinationCIDRBlock != nil {
		in, out := &in.DestinationCIDRBlock, &out.DestinationCIDRBlock
		*out = new(string)
		**out = **in
	}
	if in.PrefixListID != nil {
		in, out := &in.PrefixListID, &out.PrefixListID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRoute.
func (in *NetworkRoute) DeepCopy() *NetworkRoute {
	if in == nil {
		return nil
	}
	out := new(NetworkRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRouteDestination) DeepCopyInto(out *NetworkRouteDestination) {
	*out = *in
	if in.NetworkFunctionGroupName != nil {
		in, out := &in.NetworkFunctionGroupName, &out.NetworkFunctionGroupName
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.SegmentName != nil {
		in, out := &in.SegmentName, &out.SegmentName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRouteDestination.
func (in *NetworkRouteDestination) DeepCopy() *NetworkRouteDestination {
	if in == nil {
		return nil
	}
	out := new(NetworkRouteDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkTelemetry) DeepCopyInto(out *NetworkTelemetry) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkTelemetry.
func (in *NetworkTelemetry) DeepCopy() *NetworkTelemetry {
	if in == nil {
		return nil
	}
	out := new(NetworkTelemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathComponent) DeepCopyInto(out *PathComponent) {
	*out = *in
	if in.DestinationCIDRBlock != nil {
		in, out := &in.DestinationCIDRBlock, &out.DestinationCIDRBlock
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathComponent.
func (in *PathComponent) DeepCopy() *PathComponent {
	if in == nil {
		return nil
	}
	out := new(PathComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Peering) DeepCopyInto(out *Peering) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Peering.
func (in *Peering) DeepCopy() *Peering {
	if in == nil {
		return nil
	}
	out := new(Peering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixListAssociation) DeepCopyInto(out *PrefixListAssociation) {
	*out = *in
	if in.PrefixListAlias != nil {
		in, out := &in.PrefixListAlias, &out.PrefixListAlias
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixListAssociation.
func (in *PrefixListAssociation) DeepCopy() *PrefixListAssociation {
	if in == nil {
		return nil
	}
	out := new(PrefixListAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposedNetworkFunctionGroupChange) DeepCopyInto(out *ProposedNetworkFunctionGroupChange) {
	*out = *in
	if in.NetworkFunctionGroupName != nil {
		in, out := &in.NetworkFunctionGroupName, &out.NetworkFunctionGroupName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposedNetworkFunctionGroupChange.
func (in *ProposedNetworkFunctionGroupChange) DeepCopy() *ProposedNetworkFunctionGroupChange {
	if in == nil {
		return nil
	}
	out := new(ProposedNetworkFunctionGroupChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposedSegmentChange) DeepCopyInto(out *ProposedSegmentChange) {
	*out = *in
	if in.SegmentName != nil {
		in, out := &in.SegmentName, &out.SegmentName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposedSegmentChange.
func (in *ProposedSegmentChange) DeepCopy() *ProposedSegmentChange {
	if in == nil {
		return nil
	}
	out := new(ProposedSegmentChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Relationship) DeepCopyInto(out *Relationship) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Relationship.
func (in *Relationship) DeepCopy() *Relationship {
	if in == nil {
		return nil
	}
	out := new(Relationship)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteAnalysis) DeepCopyInto(out *RouteAnalysis) {
	*out = *in
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
	if in.RouteAnalysisID != nil {
		in, out := &in.RouteAnalysisID, &out.RouteAnalysisID
		*out = new(string)
		**out = **in
	}
	if in.StartTimestamp != nil {
		in, out := &in.StartTimestamp, &out.StartTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteAnalysis.
func (in *RouteAnalysis) DeepCopy() *RouteAnalysis {
	if in == nil {
		return nil
	}
	out := new(RouteAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingInformationNextHop) DeepCopyInto(out *RoutingInformationNextHop) {
	*out = *in
	if in.CoreNetworkAttachmentID != nil {
		in, out := &in.CoreNetworkAttachmentID, &out.CoreNetworkAttachmentID
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.SegmentName != nil {
		in, out := &in.SegmentName, &out.SegmentName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingInformationNextHop.
func (in *RoutingInformationNextHop) DeepCopy() *RoutingInformationNextHop {
	if in == nil {
		return nil
	}
	out := new(RoutingInformationNextHop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Site) DeepCopyInto(out *Site) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Site.
func (in *Site) DeepCopy() *Site {
	if in == nil {
		return nil
	}
	out := new(Site)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayConnectPeerAssociation) DeepCopyInto(out *TransitGatewayConnectPeerAssociation) {
	*out = *in
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayConnectPeerAssociation.
func (in *TransitGatewayConnectPeerAssociation) DeepCopy() *TransitGatewayConnectPeerAssociation {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayConnectPeerAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayRegistration) DeepCopyInto(out *TransitGatewayRegistration) {
	*out = *in
	if in.GlobalNetworkID != nil {
		in, out := &in.GlobalNetworkID, &out.GlobalNetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayRegistration.
func (in *TransitGatewayRegistration) DeepCopy() *TransitGatewayRegistration {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitGatewayRegistrationStateReason) DeepCopyInto(out *TransitGatewayRegistrationStateReason) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitGatewayRegistrationStateReason.
func (in *TransitGatewayRegistrationStateReason) DeepCopy() *TransitGatewayRegistrationStateReason {
	if in == nil {
		return nil
	}
	out := new(TransitGatewayRegistrationStateReason)
	in.DeepCopyInto(out)
	return out
}
