// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package connect_peer

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.BGPOptions, b.ko.Spec.BGPOptions) {
		delta.Add("Spec.BGPOptions", a.ko.Spec.BGPOptions, b.ko.Spec.BGPOptions)
	} else if a.ko.Spec.BGPOptions != nil && b.ko.Spec.BGPOptions != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.BGPOptions.PeerASN, b.ko.Spec.BGPOptions.PeerASN) {
			delta.Add("Spec.BGPOptions.PeerASN", a.ko.Spec.BGPOptions.PeerASN, b.ko.Spec.BGPOptions.PeerASN)
		} else if a.ko.Spec.BGPOptions.PeerASN != nil && b.ko.Spec.BGPOptions.PeerASN != nil {
			if *a.ko.Spec.BGPOptions.PeerASN != *b.ko.Spec.BGPOptions.PeerASN {
				delta.Add("Spec.BGPOptions.PeerASN", a.ko.Spec.BGPOptions.PeerASN, b.ko.Spec.BGPOptions.PeerASN)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ConnectAttachmentID, b.ko.Spec.ConnectAttachmentID) {
		delta.Add("Spec.ConnectAttachmentID", a.ko.Spec.ConnectAttachmentID, b.ko.Spec.ConnectAttachmentID)
	} else if a.ko.Spec.ConnectAttachmentID != nil && b.ko.Spec.ConnectAttachmentID != nil {
		if *a.ko.Spec.ConnectAttachmentID != *b.ko.Spec.ConnectAttachmentID {
			delta.Add("Spec.ConnectAttachmentID", a.ko.Spec.ConnectAttachmentID, b.ko.Spec.ConnectAttachmentID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CoreNetworkAddress, b.ko.Spec.CoreNetworkAddress) {
		delta.Add("Spec.CoreNetworkAddress", a.ko.Spec.CoreNetworkAddress, b.ko.Spec.CoreNetworkAddress)
	} else if a.ko.Spec.CoreNetworkAddress != nil && b.ko.Spec.CoreNetworkAddress != nil {
		if *a.ko.Spec.CoreNetworkAddress != *b.ko.Spec.CoreNetworkAddress {
			delta.Add("Spec.CoreNetworkAddress", a.ko.Spec.CoreNetworkAddress, b.ko.Spec.CoreNetworkAddress)
		}
	}
	if len(a.ko.Spec.InsideCIDRBlocks) != len(b.ko.Spec.InsideCIDRBlocks) {
		delta.Add("Spec.InsideCIDRBlocks", a.ko.Spec.InsideCIDRBlocks, b.ko.Spec.InsideCIDRBlocks)
	} else if len(a.ko.Spec.InsideCIDRBlocks) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.InsideCIDRBlocks, b.ko.Spec.InsideCIDRBlocks) {
			delta.Add("Spec.InsideCIDRBlocks", a.ko.Spec.InsideCIDRBlocks, b.ko.Spec.InsideCIDRBlocks)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PeerAddress, b.ko.Spec.PeerAddress) {
		delta.Add("Spec.PeerAddress", a.ko.Spec.PeerAddress, b.ko.Spec.PeerAddress)
	} else if a.ko.Spec.PeerAddress != nil && b.ko.Spec.PeerAddress != nil {
		if *a.ko.Spec.PeerAddress != *b.ko.Spec.PeerAddress {
			delta.Add("Spec.PeerAddress", a.ko.Spec.PeerAddress, b.ko.Spec.PeerAddress)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SubnetARN, b.ko.Spec.SubnetARN) {
		delta.Add("Spec.SubnetARN", a.ko.Spec.SubnetARN, b.ko.Spec.SubnetARN)
	} else if a.ko.Spec.SubnetARN != nil && b.ko.Spec.SubnetARN != nil {
		if *a.ko.Spec.SubnetARN != *b.ko.Spec.SubnetARN {
			delta.Add("Spec.SubnetARN", a.ko.Spec.SubnetARN, b.ko.Spec.SubnetARN)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
