// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package connect_peer

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/networkmanager"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/networkmanager/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/networkmanager-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ConnectPeer{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetConnectPeerOutput
	resp, err = rm.sdkapi.GetConnectPeer(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetConnectPeer", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.ConnectPeer.Configuration != nil {
		f0 := &svcapitypes.ConnectPeerConfiguration{}
		if resp.ConnectPeer.Configuration.BgpConfigurations != nil {
			f0f0 := []*svcapitypes.ConnectPeerBGPConfiguration{}
			for _, f0f0iter := range resp.ConnectPeer.Configuration.BgpConfigurations {
				f0f0elem := &svcapitypes.ConnectPeerBGPConfiguration{}
				if f0f0iter.CoreNetworkAddress != nil {
					f0f0elem.CoreNetworkAddress = f0f0iter.CoreNetworkAddress
				}
				if f0f0iter.CoreNetworkAsn != nil {
					f0f0elem.CoreNetworkASN = f0f0iter.CoreNetworkAsn
				}
				if f0f0iter.PeerAddress != nil {
					f0f0elem.PeerAddress = f0f0iter.PeerAddress
				}
				if f0f0iter.PeerAsn != nil {
					f0f0elem.PeerASN = f0f0iter.PeerAsn
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.BGPConfigurations = f0f0
		}
		if resp.ConnectPeer.Configuration.CoreNetworkAddress != nil {
			f0.CoreNetworkAddress = resp.ConnectPeer.Configuration.CoreNetworkAddress
		}
		if resp.ConnectPeer.Configuration.InsideCidrBlocks != nil {
			f0.InsideCIDRBlocks = aws.StringSlice(resp.ConnectPeer.Configuration.InsideCidrBlocks)
		}
		if resp.ConnectPeer.Configuration.PeerAddress != nil {
			f0.PeerAddress = resp.ConnectPeer.Configuration.PeerAddress
		}
		if resp.ConnectPeer.Configuration.Protocol != "" {
			f0.Protocol = aws.String(string(resp.ConnectPeer.Configuration.Protocol))
		}
		ko.Status.Configuration = f0
	} else {
		ko.Status.Configuration = nil
	}
	if resp.ConnectPeer.ConnectAttachmentId != nil {
		ko.Spec.ConnectAttachmentID = resp.ConnectPeer.ConnectAttachmentId
	} else {
		ko.Spec.ConnectAttachmentID = nil
	}
	if resp.ConnectPeer.ConnectPeerId != nil {
		ko.Status.ConnectPeerID = resp.ConnectPeer.ConnectPeerId
	} else {
		ko.Status.ConnectPeerID = nil
	}
	if resp.ConnectPeer.CoreNetworkId != nil {
		ko.Status.CoreNetworkID = resp.ConnectPeer.CoreNetworkId
	} else {
		ko.Status.CoreNetworkID = nil
	}
	if resp.ConnectPeer.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.ConnectPeer.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.ConnectPeer.EdgeLocation != nil {
		ko.Status.EdgeLocation = resp.ConnectPeer.EdgeLocation
	} else {
		ko.Status.EdgeLocation = nil
	}
	if resp.ConnectPeer.LastModificationErrors != nil {
		f6 := []*svcapitypes.ConnectPeerError{}
		for _, f6iter := range resp.ConnectPeer.LastModificationErrors {
			f6elem := &svcapitypes.ConnectPeerError{}
			if f6iter.Code != "" {
				f6elem.Code = aws.String(string(f6iter.Code))
			}
			if f6iter.Message != nil {
				f6elem.Message = f6iter.Message
			}
			if f6iter.RequestId != nil {
				f6elem.RequestID = f6iter.RequestId
			}
			if f6iter.ResourceArn != nil {
				f6elem.ResourceARN = f6iter.ResourceArn
			}
			f6 = append(f6, f6elem)
		}
		ko.Status.LastModificationErrors = f6
	} else {
		ko.Status.LastModificationErrors = nil
	}
	if resp.ConnectPeer.State != "" {
		ko.Status.State = aws.String(string(resp.ConnectPeer.State))
	} else {
		ko.Status.State = nil
	}
	if resp.ConnectPeer.SubnetArn != nil {
		ko.Spec.SubnetARN = resp.ConnectPeer.SubnetArn
	} else {
		ko.Spec.SubnetARN = nil
	}
	if resp.ConnectPeer.Tags != nil {
		f9 := []*svcapitypes.Tag{}
		for _, f9iter := range resp.ConnectPeer.Tags {
			f9elem := &svcapitypes.Tag{}
			if f9iter.Key != nil {
				f9elem.Key = f9iter.Key
			}
			if f9iter.Value != nil {
				f9elem.Value = f9iter.Value
			}
			f9 = append(f9, f9elem)
		}
		ko.Spec.Tags = f9
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ConnectPeerID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetConnectPeerInput, error) {
	res := &svcsdk.GetConnectPeerInput{}

	if r.ko.Status.ConnectPeerID != nil {
		res.ConnectPeerId = r.ko.Status.ConnectPeerID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateConnectPeerOutput
	_ = resp
	resp, err = rm.sdkapi.CreateConnectPeer(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateConnectPeer", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ConnectPeer.Configuration != nil {
		f0 := &svcapitypes.ConnectPeerConfiguration{}
		if resp.ConnectPeer.Configuration.BgpConfigurations != nil {
			f0f0 := []*svcapitypes.ConnectPeerBGPConfiguration{}
			for _, f0f0iter := range resp.ConnectPeer.Configuration.BgpConfigurations {
				f0f0elem := &svcapitypes.ConnectPeerBGPConfiguration{}
				if f0f0iter.CoreNetworkAddress != nil {
					f0f0elem.CoreNetworkAddress = f0f0iter.CoreNetworkAddress
				}
				if f0f0iter.CoreNetworkAsn != nil {
					f0f0elem.CoreNetworkASN = f0f0iter.CoreNetworkAsn
				}
				if f0f0iter.PeerAddress != nil {
					f0f0elem.PeerAddress = f0f0iter.PeerAddress
				}
				if f0f0iter.PeerAsn != nil {
					f0f0elem.PeerASN = f0f0iter.PeerAsn
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.BGPConfigurations = f0f0
		}
		if resp.ConnectPeer.Configuration.CoreNetworkAddress != nil {
			f0.CoreNetworkAddress = resp.ConnectPeer.Configuration.CoreNetworkAddress
		}
		if resp.ConnectPeer.Configuration.InsideCidrBlocks != nil {
			f0.InsideCIDRBlocks = aws.StringSlice(resp.ConnectPeer.Configuration.InsideCidrBlocks)
		}
		if resp.ConnectPeer.Configuration.PeerAddress != nil {
			f0.PeerAddress = resp.ConnectPeer.Configuration.PeerAddress
		}
		if resp.ConnectPeer.Configuration.Protocol != "" {
			f0.Protocol = aws.String(string(resp.ConnectPeer.Configuration.Protocol))
		}
		ko.Status.Configuration = f0
	} else {
		ko.Status.Configuration = nil
	}
	if resp.ConnectPeer.ConnectAttachmentId != nil {
		ko.Spec.ConnectAttachmentID = resp.ConnectPeer.ConnectAttachmentId
	} else {
		ko.Spec.ConnectAttachmentID = nil
	}
	if resp.ConnectPeer.ConnectPeerId != nil {
		ko.Status.ConnectPeerID = resp.ConnectPeer.ConnectPeerId
	} else {
		ko.Status.ConnectPeerID = nil
	}
	if resp.ConnectPeer.CoreNetworkId != nil {
		ko.Status.CoreNetworkID = resp.ConnectPeer.CoreNetworkId
	} else {
		ko.Status.CoreNetworkID = nil
	}
	if resp.ConnectPeer.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.ConnectPeer.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.ConnectPeer.EdgeLocation != nil {
		ko.Status.EdgeLocation = resp.ConnectPeer.EdgeLocation
	} else {
		ko.Status.EdgeLocation = nil
	}
	if resp.ConnectPeer.LastModificationErrors != nil {
		f6 := []*svcapitypes.ConnectPeerError{}
		for _, f6iter := range resp.ConnectPeer.LastModificationErrors {
			f6elem := &svcapitypes.ConnectPeerError{}
			if f6iter.Code != "" {
				f6elem.Code = aws.String(string(f6iter.Code))
			}
			if f6iter.Message != nil {
				f6elem.Message = f6iter.Message
			}
			if f6iter.RequestId != nil {
				f6elem.RequestID = f6iter.RequestId
			}
			if f6iter.ResourceArn != nil {
				f6elem.ResourceARN = f6iter.ResourceArn
			}
			f6 = append(f6, f6elem)
		}
		ko.Status.LastModificationErrors = f6
	} else {
		ko.Status.LastModificationErrors = nil
	}
	if resp.ConnectPeer.State != "" {
		ko.Status.State = aws.String(string(resp.ConnectPeer.State))
	} else {
		ko.Status.State = nil
	}
	if resp.ConnectPeer.SubnetArn != nil {
		ko.Spec.SubnetARN = resp.ConnectPeer.SubnetArn
	} else {
		ko.Spec.SubnetARN = nil
	}
	if resp.ConnectPeer.Tags != nil {
		f9 := []*svcapitypes.Tag{}
		for _, f9iter := range resp.ConnectPeer.Tags {
			f9elem := &svcapitypes.Tag{}
			if f9iter.Key != nil {
				f9elem.Key = f9iter.Key
			}
			if f9iter.Value != nil {
				f9elem.Value = f9iter.Value
			}
			f9 = append(f9, f9elem)
		}
		ko.Spec.Tags = f9
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateConnectPeerInput, error) {
	res := &svcsdk.CreateConnectPeerInput{}

	if r.ko.Spec.BGPOptions != nil {
		f0 := &svcsdktypes.BgpOptions{}
		if r.ko.Spec.BGPOptions.PeerASN != nil {
			f0.PeerAsn = r.ko.Spec.BGPOptions.PeerASN
		}
		res.BgpOptions = f0
	}
	if r.ko.Spec.ConnectAttachmentID != nil {
		res.ConnectAttachmentId = r.ko.Spec.ConnectAttachmentID
	}
	if r.ko.Spec.CoreNetworkAddress != nil {
		res.CoreNetworkAddress = r.ko.Spec.CoreNetworkAddress
	}
	if r.ko.Spec.InsideCIDRBlocks != nil {
		res.InsideCidrBlocks = aws.ToStringSlice(r.ko.Spec.InsideCIDRBlocks)
	}
	if r.ko.Spec.PeerAddress != nil {
		res.PeerAddress = r.ko.Spec.PeerAddress
	}
	if r.ko.Spec.SubnetARN != nil {
		res.SubnetArn = r.ko.Spec.SubnetARN
	}
	if r.ko.Spec.Tags != nil {
		f6 := []svcsdktypes.Tag{}
		for _, f6iter := range r.ko.Spec.Tags {
			f6elem := &svcsdktypes.Tag{}
			if f6iter.Key != nil {
				f6elem.Key = f6iter.Key
			}
			if f6iter.Value != nil {
				f6elem.Value = f6iter.Value
			}
			f6 = append(f6, *f6elem)
		}
		res.Tags = f6
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return nil, ackerr.NewTerminalError(ackerr.NotImplemented)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteConnectPeerOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteConnectPeer(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteConnectPeer", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteConnectPeerInput, error) {
	res := &svcsdk.DeleteConnectPeerInput{}

	if r.ko.Status.ConnectPeerID != nil {
		res.ConnectPeerId = r.ko.Status.ConnectPeerID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ConnectPeer,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"AccessDeniedException":
		return true
	default:
		return false
	}
}
