// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package connect_attachment

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.CoreNetworkID, b.ko.Spec.CoreNetworkID) {
		delta.Add("Spec.CoreNetworkID", a.ko.Spec.CoreNetworkID, b.ko.Spec.CoreNetworkID)
	} else if a.ko.Spec.CoreNetworkID != nil && b.ko.Spec.CoreNetworkID != nil {
		if *a.ko.Spec.CoreNetworkID != *b.ko.Spec.CoreNetworkID {
			delta.Add("Spec.CoreNetworkID", a.ko.Spec.CoreNetworkID, b.ko.Spec.CoreNetworkID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EdgeLocation, b.ko.Spec.EdgeLocation) {
		delta.Add("Spec.EdgeLocation", a.ko.Spec.EdgeLocation, b.ko.Spec.EdgeLocation)
	} else if a.ko.Spec.EdgeLocation != nil && b.ko.Spec.EdgeLocation != nil {
		if *a.ko.Spec.EdgeLocation != *b.ko.Spec.EdgeLocation {
			delta.Add("Spec.EdgeLocation", a.ko.Spec.EdgeLocation, b.ko.Spec.EdgeLocation)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Options, b.ko.Spec.Options) {
		delta.Add("Spec.Options", a.ko.Spec.Options, b.ko.Spec.Options)
	} else if a.ko.Spec.Options != nil && b.ko.Spec.Options != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Options.Protocol, b.ko.Spec.Options.Protocol) {
			delta.Add("Spec.Options.Protocol", a.ko.Spec.Options.Protocol, b.ko.Spec.Options.Protocol)
		} else if a.ko.Spec.Options.Protocol != nil && b.ko.Spec.Options.Protocol != nil {
			if *a.ko.Spec.Options.Protocol != *b.ko.Spec.Options.Protocol {
				delta.Add("Spec.Options.Protocol", a.ko.Spec.Options.Protocol, b.ko.Spec.Options.Protocol)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoutingPolicyLabel, b.ko.Spec.RoutingPolicyLabel) {
		delta.Add("Spec.RoutingPolicyLabel", a.ko.Spec.RoutingPolicyLabel, b.ko.Spec.RoutingPolicyLabel)
	} else if a.ko.Spec.RoutingPolicyLabel != nil && b.ko.Spec.RoutingPolicyLabel != nil {
		if *a.ko.Spec.RoutingPolicyLabel != *b.ko.Spec.RoutingPolicyLabel {
			delta.Add("Spec.RoutingPolicyLabel", a.ko.Spec.RoutingPolicyLabel, b.ko.Spec.RoutingPolicyLabel)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TransportAttachmentID, b.ko.Spec.TransportAttachmentID) {
		delta.Add("Spec.TransportAttachmentID", a.ko.Spec.TransportAttachmentID, b.ko.Spec.TransportAttachmentID)
	} else if a.ko.Spec.TransportAttachmentID != nil && b.ko.Spec.TransportAttachmentID != nil {
		if *a.ko.Spec.TransportAttachmentID != *b.ko.Spec.TransportAttachmentID {
			delta.Add("Spec.TransportAttachmentID", a.ko.Spec.TransportAttachmentID, b.ko.Spec.TransportAttachmentID)
		}
	}

	return delta
}
